### ISSUE TITLE
Create a Icon Button 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#10]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-6](https://user-images.githubusercontent.com/91758830/195206163-ffd4c88f-e72a-4d6e-994d-dde6ebc23c8c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/ic0n_button_rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by prakrit55** [comment]
Hey I would like to work on this issue :)

**Comment by Rajdip019** [comment]
Sure go ahead. @prakrit55

**Comment by Hiresh23** [comment]
i would like to contribute ,to this issue

**Comment by rupsha014** [comment]
this issue is resolved.
