### ISSUE TITLE
Create a Pricing Component

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#105]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![pricing-style-1](https://user-images.githubusercontent.com/76204863/195662179-ff266c35-5614-4605-9975-956e1c0f9bdf.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by infuman69** [comment]
Can I work on this issue ?

**Comment by ThisisMS11** [comment]
Can you assign this one to me ? I have the necessary experience for this issue.

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue. @rahulkarda
