### ISSUE TITLE
Create a Subscribe Newsletter

### ISSUE THREAD

**Issue by infuman69** [Clueless-Community/web-ui-kit#107]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![image](https://user-images.githubusercontent.com/81096719/195670530-c3d78ea8-c88f-4b10-bce5-399a3d9e6e06.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by infuman69** [comment]
Can I work on this Issue ?

**Comment by ThisisMS11** [comment]
I have recently done a lot of work using the same tech ,so can you please assign this one to me?

**Comment by Rajdip019** [comment]
Go ahead @infuman69 . Here is first come first serve sorry @ThisisMS11

**Comment by infuman69** [comment]
thanks : )

**Comment by Rajdip019** [comment]
Closing this issue as it is solved.
