### ISSUE TITLE
Create a Icon Button Rounded

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#11]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![btn-sm-15](https://user-images.githubusercontent.com/91758830/195206308-1b3e2b73-2a21-4fdc-a179-5dbad308518e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/icon_button_rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by snikoletopoulos** [comment]
Hello, can I contribute to this?

**Comment by Rajdip019** [comment]
Sure. @snikoletopoulos

**Comment by Rajdip019** [comment]
This issue is resolved so closing this PR. @snikoletopoulos
