### ISSUE TITLE
Create a Simple features card small

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#110]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-4](https://user-images.githubusercontent.com/91758830/195685392-aa5c9156-adc8-4e38-a4f4-92017c0fc830.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/simple-features-card-small.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jesulonimii** [comment]
Please i want to work on this

**Comment by Rajdip019** [comment]
You are already assigned in an issue. @jesulonimii

**Comment by jesulonimii** [comment]
I have completed that issue

**Comment by pikameow420** [comment]
I'd like to work on this issue

**Comment by Rajdip019** [comment]
Go ahead @pikameow420 and @jesulonimii I have assigned you another issue.

**Comment by pikameow420** [comment]
Created a PR
Please accept and merge if its satisfactory.
Thank you.
