### ISSUE TITLE
Create a job security card-1

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#111]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![card-item-5](https://user-images.githubusercontent.com/109761128/195685385-5f4f3eed-10ac-4bd5-bc4c-ec22db31a163.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/feature-cards-job-security1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by hritikbhattacharya** [comment]
@rupsha014 assign it to me..

**Comment by DarkSoul26** [comment]
Hi @rupsha014 I would like to work on this issue.

**Comment by udoyhasan** [comment]
@rupsha014 please assign me. I'd like to work on this issue.

**Comment by Rajdip019** [comment]
Go ahead @DarkSoul26

**Comment by DarkSoul26** [comment]
@Rajdip019 @rupsha014 can you take a look into the #186 where I have added the details of this issue.

**Comment by DarkSoul26** [comment]
@Rajdip019 please take a look into this #186
