### ISSUE TITLE
Create a feature card(small outlined)

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#113]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![card-item-2](https://user-images.githubusercontent.com/109761128/195687050-3b6df3c8-89da-4318-8bb7-cc303e741671.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/feature-card-small-outlined.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by hritikbhattacharya** [comment]
@rupsha014 assign it to me

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @hritikbhattacharya

**Comment by Upasana-Roy** [comment]
Can you please assign it to me

**Comment by Rajdip019** [comment]
Go ahead @Upasana-Roy
