### ISSUE TITLE
Create a Features card medium filled

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#114]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-8](https://user-images.githubusercontent.com/91758830/195687438-5172eea1-6d78-4755-bea2-bfc79bc4687d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Features Card/features-card-medium-filled.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by devjain2309** [comment]
please assign me this

**Comment by Rajdip019** [comment]
You have already been assigned to an issue. @devjain2309

**Comment by devjain2309** [comment]
It's completed now. You can assign me this.

**Comment by Rajdip019** [comment]
Sure @devjain2309

**Comment by Rajdip019** [comment]
But first check the comment on the previous PR.

**Comment by devjain2309** [comment]
@Rajdip019 please check my previous PR and if you found it right then assign me this.

**Comment by MadhurKharche** [comment]
Allow me to work on this issue.

**Comment by Rajdip019** [comment]
Are you still working on this issue? @devjain2309
