### ISSUE TITLE
Create a Feature Card medium outlined with button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#115]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-10](https://user-images.githubusercontent.com/91758830/195688064-820baeaf-c277-4be9-9962-b4e78956c78d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Features Card/feature-card-medium-oulined-button.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by devjain2309** [comment]
Can I do This

**Comment by Rajdip019** [comment]
You are already assigned to an issue finish that  one first. @devjain2309

**Comment by tauleshwar** [comment]
Let me work on this one .

**Comment by Rajdip019** [comment]
Sure @tauleshwar

**Comment by MadhurKharche** [comment]
I would like to work on this issue. Allow me to contribute to this issue
