### ISSUE TITLE
Create a Feature Card large outlined with button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#117]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-13](https://user-images.githubusercontent.com/91758830/195688587-b8a79cf7-3811-44e4-918b-217f42b408e3.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Card/feature-card-large-outlined-button.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by hritikbhattacharya** [comment]
thank you for assigning this to me
