### ISSUE TITLE
Create a appointment card

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#118]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![card-item-12](https://user-images.githubusercontent.com/109761128/195688861-67007e18-51bb-4473-9a7f-766b6e46322c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/feature-cards-appointment-card.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nishilpjpt** [comment]
@rupsha014 I would like to  try out this can you assign me ?

**Comment by Rajdip019** [comment]
Go ahead @nishilpjpt
