### ISSUE TITLE
Create a Feature Card Stats percent

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#119]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-14](https://user-images.githubusercontent.com/91758830/195688926-3102c0e1-a2c2-4291-ac24-f285e2d0c545.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Card/features-card-stats-percent.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jesulonimii** [comment]
Please let me work on this

**Comment by Rajdip019** [comment]
Go ahead @jesulonimii
