### ISSUE TITLE
Create a Primary Button Rounded

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#12]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-10](https://user-images.githubusercontent.com/91758830/195206455-6af2537e-81ff-4ba2-ad32-727210dd22df.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/button_primary_rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by aabhas-sao** [comment]
hey @Rajdip019, please assign me this. I would like to work on this issue.

**Comment by Rajdip019** [comment]
Go ahead @aabhas-sao

**Comment by Hiresh23** [comment]
i would like to work on this issue

**Comment by Rajdip019** [comment]
Closing this issue as it is solved. @aabhas-sao
