### ISSUE TITLE
Create a Simple features card small v2

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#120]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![card-item-15](https://user-images.githubusercontent.com/91758830/195689525-777fc666-4898-4aef-a39c-2afd7a675a41.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Card/features-card-small-v2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Anadee11** [comment]
I just need to create a small card with the icon and the text with Tailwind and HTML right?
If yes, could you please assign this to me!

**Comment by Rajdip019** [comment]
Yes. Go ahead build it. @Anadee11
