### ISSUE TITLE
Create a job security card-2

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#121]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![card-item-16](https://user-images.githubusercontent.com/109761128/195689607-10571851-b328-4075-b618-3eb591c547da.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/feature-cards-job-security2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jesulonimii** [comment]
I would like to wotk on this

**Comment by Rajdip019** [comment]
Go ahead @jesulonimii
