### ISSUE TITLE
Create a feature card(medium outlined)

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#124]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![card-item-9](https://user-images.githubusercontent.com/109761128/195690819-9d702950-d603-4d6a-b982-4e22ce3ff792.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Card/feature-card-medium-outlined.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by devjain2309** [comment]
assign me, i'll try it

**Comment by Rajdip019** [comment]
Go ahead @devjain2309

**Comment by MadhurKharche** [comment]
I would like to work on this issue. Please assign me this issue.
