### ISSUE TITLE
Create a job security card(filled)

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#125]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![card-item-6](https://user-images.githubusercontent.com/109761128/195691397-30488ae3-ecb9-40b0-8fb8-f875dacf44ed.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Feature Cards/feature-card-job -security-filled.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by aritra-tech** [comment]
Can I work on this issue @rupsha014

**Comment by rupsha014** [comment]
go ahead @aritra-tech

**Comment by MadhurKharche** [comment]
I wish to contribute to this issue. Please assign this issue to me @rupsha014

**Comment by aritra-tech** [comment]
> I wish to contribute to this issue. Please assign this issue to me @rupsha014

Ok @MadhurKharche you continue with this issue I will do the other issues.
@rupsha014 please assign it to @MadhurKharche

**Comment by DarkSoul26** [comment]
Hi @rupsha014 I would like to work on this issue

**Comment by MadhurKharche** [comment]
I have added the PR for this issue
![Screenshot (2861)](https://user-images.githubusercontent.com/78757405/195915306-9701c309-0aff-4412-b457-754a35bc4902.png)
