### ISSUE TITLE
Create a Secondary Button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#13]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-19](https://user-images.githubusercontent.com/91758830/195206597-8b5f6c06-d7a8-4b5f-ab58-10cce92b225e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/button_secondary.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by sfrunza13** [comment]
Hi, I would like to take on this issue

**Comment by Rajdip019** [comment]
You are already assigned in two issues. Fix then and then I will assign this to you.

**Comment by Rajdip019** [comment]
You are already assigned in two issues. Fix then and then I will assign this to you.

**Comment by aritra-tech** [comment]
Can I work on this issue @Rajdip019

**Comment by Rajdip019** [comment]
Sure go ahead @aritra-tech

**Comment by rupsha014** [comment]
issue is resolved
