### ISSUE TITLE
Create a table for dark mode

### ISSUE THREAD

**Issue by nishit3134** [Clueless-Community/web-ui-kit#134]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/111650900/195749021-4fdfcfee-0828-42c6-8b04-e2553b6ed210.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nishit3134** [comment]
@Rajdip019 please assign me this issue

**Comment by Rajdip019** [comment]
Go ahead build it. @nishit3134

**Comment by Hiresh23** [comment]
i would like to contribute
