### ISSUE TITLE
Create a desktop filter component

### ISSUE THREAD

**Issue by abhijain2003** [Clueless-Community/web-ui-kit#136]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Hey I wanted to contribute more to this repo kindly assign this to me 
Here is a reference to the component. 
#### Add image here
![Screenshot 2022-10-14 111801](https://user-images.githubusercontent.com/91718608/195771304-ba837626-20da-478c-be27-fa5976e431f2.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Choose one @abhijain2003

**Comment by abhijain2003** [comment]
is this not one, ok then I would like to go with accessories

**Comment by Rajdip019** [comment]
Ok go with it and update the image @abhijain2003

**Comment by abhijain2003** [comment]
sure

**Comment by abhijain2003** [comment]
just wanted to confirm is the location of this component will be Filter/Desktop/marketplace.html

**Comment by Rajdip019** [comment]
`marketplace-1.html` @abhijain2003

**Comment by abhijain2003** [comment]
sure
