### ISSUE TITLE
Create a Contact Us component

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#137]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![contactus](https://user-images.githubusercontent.com/76204863/195774091-87550f8e-a639-49cf-bcb0-99d6782cc3dd.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bharat24835** [comment]
Can I contribute without using Tailwind CSS, using Simple CSS

**Comment by rupsha014** [comment]
go ahead @rahulkarda

**Comment by rupsha014** [comment]
> Can I contribute without using Tailwind CSS, using Simple CSS

no..... you have to use tailwind CSS to contribute in this repository

**Comment by rahulkarda** [comment]
> go ahead @rahulkarda

Done. I've created a PR.

**Comment by rahulkarda** [comment]
@rupsha014 close this issue, it's already merged.
