### ISSUE TITLE
Create input components

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#139]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![inputs](https://user-images.githubusercontent.com/76204863/195776858-36fd1ed7-150d-4b38-ab0a-8d185dc5ddde.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
Please assign me this issue

**Comment by rahulkarda** [comment]
> Please assign me this issue

I'm already working on it.

**Comment by rupsha014** [comment]
> > Please assign me this issue
> 
> I'm already working on it.

you have already been assingned a issue .....please complete that first

**Comment by rupsha014** [comment]
go ahead @jsvigneshkanna

**Comment by rahulkarda** [comment]
> > > Please assign me this issue
> > 
> > 
> > I'm already working on it.
> 
> you have already been assingned a issue .....please complete that first

I already completed my previous issue. Reassign this issue to me please.

**Comment by Rajdip019** [comment]
Hey, @rahulkarda sorry but this component is not there in the Figma file right? @rahulkarda

**Comment by rahulkarda** [comment]
> Hey, @rahulkarda sorry but this component is not there in the Figma file right? @rahulkarda

There were individual input boxes here and there in the figma file, I compiled all of them into one.

**Comment by Rajdip019** [comment]
The style is not same and we need them in different files as well. So closing this issue right now. You can make a new issue with one input field at a time @rahulkarda

**Comment by rahulkarda** [comment]
Got it!
