### ISSUE TITLE
Create a Secondary button rounded

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#14]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-28](https://user-images.githubusercontent.com/91758830/195206767-3b478231-a9c7-442c-9cdf-2e0d4de20656.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/button_secondary_rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Gunika2002** [comment]
Hey @Rajdip019 kindly assign me to this issue. I would like to work on this component

**Comment by Rajdip019** [comment]
Sure. Go ahead. @Gunika2002

**Comment by rupsha014** [comment]
@Gunika2002 ...Are you still working on this?otherwise i will assign someone else.

**Comment by Gunika2002** [comment]
@rupsha014 yes i am working on it..just need to edit the component a bit

**Comment by MadhurKharche** [comment]
Please allow me to work on this issue.

**Comment by MadhurKharche** [comment]
Please allow me to work on this issue @rupsha014 @Rajdip019
