### ISSUE TITLE
Create a Pricing Card (Style-3)

### ISSUE THREAD

**Issue by AbirSantra** [Clueless-Community/web-ui-kit#150]
Hi, I would like to build this component under Hacktoberfest

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/78201921/195878795-aa5a89fc-3638-45df-be61-510e46f34339.png)

Kindly assign me this issue if approved.
Thank you,
Abir

**Comment by Anuran12** [comment]
@AbirSantra  I would like to work on this

**Comment by Rajdip019** [comment]
Hey @AbirSantra  work on this.

**Comment by AbirSantra** [comment]
Hey @Rajdip019 , the width of the component as shown in the Figma design is the maximum width right?

**Comment by Rajdip019** [comment]
Yes. @AbirSantra
