### ISSUE TITLE
Create a Navigation Bar 

### ISSUE THREAD

**Issue by Prosecutor1x** [Clueless-Community/web-ui-kit#152]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![navbar-style-1 (1)](https://user-images.githubusercontent.com/100259871/195893800-c9601f25-08a6-43b9-9131-416b25654ee6.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Go ahead @Prosecutor1x
