### ISSUE TITLE
Create a Navigation Bar V2

### ISSUE THREAD

**Issue by Prosecutor1x** [Clueless-Community/web-ui-kit#154]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar-style-3](https://user-images.githubusercontent.com/100259871/195898566-992dc9e3-d15d-4935-89c8-1c066b396132.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
@Prosecutor1x , please assign me this issue
