### ISSUE TITLE
Create a testimonials v1

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#160]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![testimonials-card-item-2](https://user-images.githubusercontent.com/109761128/195919464-6c7299ea-afd9-4286-9722-c8ce0abe0ef1.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/testimonial-v1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
Assign me this issue @rupsha014

**Comment by Rajdip019** [comment]
You are already assigned in an issue. @jsvigneshkanna . Please finish that first.

**Comment by aritra-tech** [comment]
Can I work on this @rupsha014

**Comment by Vannent** [comment]
Hi, I've created the template. Would this be good?
![image](https://user-images.githubusercontent.com/98601749/195938177-1b54bfcd-5310-4d81-b366-34f620210800.png)

**Comment by Hiresh23** [comment]
i would like to contribute

**Comment by Hiresh23** [comment]
please assign

**Comment by udoyhasan** [comment]
@rupsha014 can I work on this issue? I've already submitted and pull request for this component in #192

**Comment by Rajdip019** [comment]
Will check that. @udoyhasan

**Comment by AmitDeka** [comment]
I have requested a PR #178

**Comment by AmitDeka** [comment]
https://www.clueless.tech/profile/40214392 @Rajdip019
