### ISSUE TITLE
Create Primary text button blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1618]
### Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/216756209-e1dd9004-2367-410b-af5f-5e531938081b.png)

---
### After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Primary/text-button.html` by replacing the existing code and rename the file to `text-button-blue.html`. 

So, In short you need to do:-
- Make the Component
- Replace the code of `Button/src/Primary/text-button.html` with your code
- Rename `text-button-rounded.html` to `text-button-blue.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on this issue.
