### ISSUE TITLE
Create Secondary button white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1621]
### Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/216757857-90e2d7d2-d6e4-4021-8325-6ad639a190cb.png)

---
### After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Secondary/text-button-white.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I will like to work on this

**Comment by rt-001** [comment]
I will like to work on this

**Comment by Rajdip019** [comment]
Go ahead @rt-001
