### ISSUE TITLE
 Create Primary button dark 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1623]
### Here is a reference to the component. 
![Screenshot_20230204_134123](https://user-images.githubusercontent.com/98400348/216756741-0133ab04-92ba-49d9-a392-74faee4eecda.png)

---
### After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Primary/text-button-black.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tanmay09516** [comment]
I would like to contribute!
