### ISSUE TITLE
 Create 3 Sizes of Primary Blue button 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1628]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/216766628-64fd9e5f-419f-45ae-aa3e-22fac6ab9caf.png)

Please Follow the [button design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) to see the padding for small, medium, large button

After building the component please raise a PR with a screenshot of the component and add the component in `text-button-blue.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on this.
