### ISSUE TITLE
Create 3 Sizes of Secondary White Button

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1629]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot_20230204_173852](https://user-images.githubusercontent.com/98400348/216766930-75ad9a72-c6dd-4498-97c1-37d5242f8c5a.png)

Please Follow the [button design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) to see the padding for small, medium, large button

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Secondary/text-button-rounded-white.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I will like to work on this

**Comment by Tanmay09516** [comment]
I could work on this!
