### ISSUE TITLE
Create 3 Primary Black Button

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1649]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/216814423-503718e6-b15b-43f4-8556-9930cd73b292.png)

Please Follow Button design system while making it

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Primary/text-button-black.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on it.
