### ISSUE TITLE
Create a  testimonial v2

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#165]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![testimonials-card-item-3](https://user-images.githubusercontent.com/109761128/195920035-288812c3-48b2-4fa8-a86d-bba2781cece0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/testimonial-v2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by amardeep911** [comment]
Plz assign this to me

**Comment by MadhurKharche** [comment]
Please assign me this issue

**Comment by Rajdip019** [comment]
You are already assigned in a issue @amardeep911 go ahead @amardeep911

**Comment by MadhurKharche** [comment]
![image](https://user-images.githubusercontent.com/78757405/195968206-9c31a5b1-62b6-4ea4-8c5b-e54502248ae8.png)
Here is the screenshot of the component. The image used is changed. I have added a PR already

**Comment by akanshaaa19** [comment]
If available Please assign this issue to me

**Comment by MadhurKharche** [comment]
> Link the PR here. @MadhurKharche

Here is the PR link [Pull #173] (https://github.com/Clueless-Community/web-ui-kit/pull/173) @Rajdip019
