### ISSUE TITLE
Create a testimonial v4

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#167]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![testimonials-card-item-8](https://user-images.githubusercontent.com/109761128/195920802-0d5ae151-6ff0-4d7b-b389-08844ab50838.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/testimonial-v4.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by 443781544** [comment]
please assign me this

**Comment by Rajdip019** [comment]
Go ahead @443781544

**Comment by AKACHI-4** [comment]
Is it still open can I work on this?
