### ISSUE TITLE
update information alert

### ISSUE THREAD

**Issue by TanmayDoesAI** [Clueless-Community/web-ui-kit#1734]
refer to the following image and the [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1)  

![information-alert](https://user-images.githubusercontent.com/85993243/217758811-64ac6a0c-4d53-4d07-aa50-3d3ba382871a.png)

to use any icon please use it from [Hero Icons](https://heroicons.com/)

After building the component please raise a PR with a screenshot of the component and update the component in `Alerts/src/info.html`

I would like to work on this on myself

**Comment by Durgesh4993** [comment]
I would like to work on this issue.

**Comment by Tanmay09516** [comment]
hey! i have already started working on these and also mentioned in the issue that I'd like to work on this..

you could look at the other available issues or you could create one yourself [How to raise a valid issue and work on it](https://github.com/Clueless-Community/seamless-ui/blob/main/CONTRIBUTING.md#raise-an-issue-and-build-a-component-you-want-to-build)
