### ISSUE TITLE
Create Content Card 10 blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1744]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot_20230209_223633](https://user-images.githubusercontent.com/98400348/217886502-16b45ef5-cc19-41a7-b8a7-bb723fca9493.png)

Follow  [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

After building the component please raise a PR with a screenshot of the component and add the component in `Content Cards/src/content-card-10-blue.html` & Please do not add hover effect in the main div
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I would like to work on this

**Comment by Tapo41** [comment]
#1752  I created this .
@RavindraP04  Please check
