### ISSUE TITLE
Create Content Card 9 Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1747]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/217887444-c20ad1fa-d545-44f2-b0f0-8d4e1d1f3303.png)

Follow  [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

After building the component please raise a PR with a screenshot of the component and add the component in `Content Cards/src/Content-Card-9.html` &  rename the file to `content-card-9-black.html`Please do not add hover effect in the main div
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tapo41** [comment]
@RavindraP04  I want to contribute to this

**Comment by Tapo41** [comment]
#1760 Done
@RavindraP04 U can check
