### ISSUE TITLE
Create a Mobile Navbar

### ISSUE THREAD

**Issue by infuman69** [Clueless-Community/web-ui-kit#177]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![image](https://user-images.githubusercontent.com/81096719/195966211-d53f76af-f721-4520-bf23-f71e2f8a5a7c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by infuman69** [comment]
@Rajdip019  Can I work on this issue ?

**Comment by prernadabi23** [comment]
can i work on this issue?

**Comment by Rajdip019** [comment]
Go ahead @infuman69
