### ISSUE TITLE
Create a textarea component

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#178]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![textarea](https://user-images.githubusercontent.com/76204863/195966492-ae314f0a-baa7-4d5b-bfed-1b768cb71896.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by ThisisMS11** [comment]
I can do this please assign this one to me.

**Comment by rahulkarda** [comment]
> I can do this please assign this one to me.

I have opened a PR already.

**Comment by ThisisMS11** [comment]
@rahulkarda  Sorry I didn't observe that.

**Comment by Rajdip019** [comment]
Assigning you right now. @rahulkarda
