### ISSUE TITLE
Create a Navbar

### ISSUE THREAD

**Issue by animesh156** [Clueless-Community/web-ui-kit#182]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![projectcopy](https://user-images.githubusercontent.com/114474707/195968992-2cd36672-c32d-4b74-a27c-6b2ba7735a5b.png)

After building the component please raise a PR with a screenshot of the component and add the component in  Navbar/new-navbar.html. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@Rajdip019  assign this to me...

**Comment by Hiresh23** [comment]
i would like to work on this

**Comment by animesh156** [comment]
@Hiresh23 bro I have raised this one for me & i have completed this, You can find other issues or make your own issue and work on it

**Comment by Rajdip019** [comment]
This is already built. So, closing this issue. @animesh156
