### ISSUE TITLE
Create testimonial 8 white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1831]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component.  
![image](https://user-images.githubusercontent.com/98400348/218835820-6b329e3e-a90e-4e8a-a269-633bc98134ea.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/src/testimonial-8-white.html` 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SHYALI** [comment]
I want to work on this issue under JWOC'23

**Comment by arjunchoudhury07** [comment]
I would like to work on this issue under JWOC.

**Comment by SHYALI** [comment]
testimonial-8-white #1854
