### ISSUE TITLE
Create Testimonial 4 Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1849]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component.  
![image](https://user-images.githubusercontent.com/98400348/219146140-66e69d69-f1dd-4593-91f2-a3160752f979.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) 

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/src/testimonial-4.html` by replacing the existing code with yours and also rename the file to `testimonial-4-black.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@RavindraP04  can I work on this issue under JWOC
