### ISSUE TITLE
Create testimonial 15 white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1873]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/219552496-50fc6911-ed26-4b89-8602-369c26a50dab.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/src/testimonial-15-white.html` & Please do not add hover effect in the main div
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc

**Comment by SakshiShah29** [comment]
I would like to contribute to this issue

**Comment by Saishreekouda** [comment]
hey i would like to work on this

**Comment by bhumi-125** [comment]
I want to work on this issue under jwoc

**Comment by Rajdip019** [comment]
Assigned you @bhumi-125

**Comment by bhumi-125** [comment]
Thanku for assigning me this task

can you tell me how much time i have to complete this task.

**Comment by bhumi-125** [comment]
I have completed the task , please check it once 
https://play.tailwindcss.com/U7WvtlSyyl
