### ISSUE TITLE
Create a Pricing-style-4

### ISSUE THREAD

**Issue by SayantanStackflow** [Clueless-Community/web-ui-kit#188]
Hi there, I would like to build this component `pricing-style-4`  as per the Figma UI file design under Hacktoberfest2022

Here is a reference to the component. 
![Screenshot (32)](https://user-images.githubusercontent.com/103353878/195973161-2220d141-446c-4198-9c38-ef8ee550dfbf.png)

If no one has yet begun, kindly assign the component issue to me.

Thank You, 
Sayantan

**Comment by Rajdip019** [comment]
Go ahead. @SayantanStackflow
