### ISSUE TITLE
Create Product card 2 blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/web-ui-kit#1893]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/219878313-9a1c3835-b716-45b8-acb3-184aca1c4458.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 
Make the component responsive too.

After building the component please raise a PR with a screenshot of the component and add the component in `Product Cards/src/product-card-2-blue.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I would like to contribute.

**Comment by SakshiShah29** [comment]
I would like to contribute to this issue
