### ISSUE TITLE
Create a secondary rounded icon button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#19]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![btn-sm-33](https://user-images.githubusercontent.com/91758830/195254790-4cc53212-9c8d-434e-b630-8386b5830d41.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/icon_button_secondary_rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by kaustav202** [comment]
let me take this up @Rajdip019

**Comment by jsvigneshkanna** [comment]
Please assign me this

**Comment by Rajdip019** [comment]
Hey @kaustav202 go ahead. And @jsvigneshkanna please choose another component there is plenty of them. @jsvigneshkanna

**Comment by kaustav202** [comment]
Does the icon have to be identical to the image @Rajdip019 ?

**Comment by Rajdip019** [comment]
Yes you can find it on Hero Icons

**Comment by kaustav202** [comment]
> Yes you can find it on Hero Icons
 
I'm not sure i could find one like this on https://heroicons.com/

@Rajdip019

**Comment by Rajdip019** [comment]
<img width="711" alt="Screenshot 2022-10-12 at 11 05 16 AM" src="https://user-images.githubusercontent.com/91758830/195258550-2fc089d6-5d21-49f2-920f-25ff319e5c0f.png">

Here it is. It is the second icon. You can change it's color using Tailwind. @kaustav202
