### ISSUE TITLE
Create a Pricing Style 5

### ISSUE THREAD

**Issue by Hiresh23** [Clueless-Community/web-ui-kit#190]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here
![Screenshot 2022-10-15 122442](https://user-images.githubusercontent.com/99505876/195973689-74a4c303-8473-4179-889c-dd2270372fe9.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Hiresh23** [comment]
please assign

**Comment by Hiresh23** [comment]
I have made it sending pull request

**Comment by Rajdip019** [comment]
Go ahead @Hiresh23

**Comment by Blanco237** [comment]
Please assign me
