### ISSUE TITLE
Create a Success Alert Modal

### ISSUE THREAD

**Issue by jesulonimii** [Clueless-Community/web-ui-kit#191]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/70331030/195973985-ed6cf90e-7b83-46a5-8f30-eb25069c757f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `/Alerts/Success-alert-modal.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jesulonimii** [comment]
Please assign me this issue

**Comment by Rajdip019** [comment]
This is not in the Figma File. So closing this PR. @jesulonimii
