### ISSUE TITLE
Create a Notification Alert Card-1

### ISSUE THREAD

**Issue by jesulonimii** [Clueless-Community/web-ui-kit#194]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/70331030/195980573-8ff99415-ae08-47a5-b981-9eb8d1f7ba39.png)

After building the component please raise a PR with a screenshot of the component and add the component in `/Alerts/notification Alert Card-1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Anuran12** [comment]
@jesulonimii  I would like to work on this..

**Comment by jesulonimii** [comment]
I'm working on it

**Comment by Rajdip019** [comment]
Go ahead @jesulonimii
