### ISSUE TITLE
Create a Contact Component

### ISSUE THREAD

**Issue by Hiresh23** [Clueless-Community/web-ui-kit#199]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here
![Screenshot 2022-10-15 170434](https://user-images.githubusercontent.com/99505876/195984330-fbcab8f2-bf48-4f96-9997-a8a97132bf1f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Hiresh23** [comment]
Please Assign

**Comment by Rajdip019** [comment]
This is already done. @Hiresh23
