### ISSUE TITLE
Create a Secondary rounded Button with icon after the text

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#20]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-32](https://user-images.githubusercontent.com/91758830/195255140-06b5fa21-a728-4393-9486-ad2f5126b7bc.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/button_secondary_icon_rounded_after.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SubhamChoudhury** [comment]
Hey @Rajdip019, can I take this up?

**Comment by Rajdip019** [comment]
Yes sure go ahead. @SubhamChoudhury

**Comment by Rajdip019** [comment]
This issue is solved. So closing this issue. @SubhamChoudhury

**Comment by SubhamChoudhury** [comment]
Sure, thank you!
