### ISSUE TITLE
Create a alert 

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/web-ui-kit#202]
Hey, I want to make this component using `HTML` and `Tailwind CSS`. I will use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Capture](https://user-images.githubusercontent.com/99159580/195988730-eba259e7-c60a-4591-bc0c-759425ce9b70.PNG) 
  
icon resource - [Hero Icons](https://heroicons.com/)

Kindly assign it to me.

**Comment by Rajdip019** [comment]
Go ahead @AKACHI-4
