### ISSUE TITLE
Create a contact/appointment form

### ISSUE THREAD

**Issue by nishit3134** [Clueless-Community/web-ui-kit#205]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/111650900/196001292-855207e4-ece0-40de-98af-60437df137ae.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nishit3134** [comment]
@Rajdip019  I would like to work on this issue

**Comment by Rajdip019** [comment]
Go ahead @nishit3134
