### ISSUE TITLE
Create a Content Card-9 

### ISSUE THREAD

**Issue by MadhurKharche** [Clueless-Community/web-ui-kit#208]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
![image](https://user-images.githubusercontent.com/78757405/196008253-8f035f55-4e71-4531-bdc9-83c998cc81ee.png)

If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by MadhurKharche** [comment]
Please assign me this issue

**Comment by Rajdip019** [comment]
Go ahead @MadhurKharche

**Comment by NitishPal2013** [comment]
@Rajdip019 I have created the Content Card 9. Can i make a pr against this issue under hactoberfest label ?
Here is the screenshot of my work on Tailwind Playground.
![Screenshot from 2022-10-16 12-15-17](https://user-images.githubusercontent.com/76246219/196022232-0dde8630-8833-474c-9b30-f41b56ced781.png)
