### ISSUE TITLE
Create a secondary button with icon after text 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#21]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-23](https://user-images.githubusercontent.com/91758830/195255775-103d4a24-b0b9-48d7-b2e1-c1a22ba16345.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/icon_button_secondary.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
Please assign this issue to my name

**Comment by Rajdip019** [comment]
Go ahead @jsvigneshkanna

**Comment by yashsarnaik22** [comment]
can I use Bootstrap buttons?

**Comment by yashsarnaik22** [comment]
Ok noted!

**Comment by yashsarnaik22** [comment]
hey @Rajdip019 I have created the buttton 'icon after text' and the file is in my local machine in buttons/icon_button_secondary.html 
can I add it and create a PR?

**Comment by Rajdip019** [comment]
Please don't make a PR for this @jsvigneshkanna is assigned and he is working on it. I will be adding more issues. Only make a PR if you get assigned. @yashsarnaik22

**Comment by Rajdip019** [comment]
This issue is solved. So closing this issue. @jsvigneshkanna
