### ISSUE TITLE
Create a Form-card-4

### ISSUE THREAD

**Issue by SayantanStackflow** [Clueless-Community/web-ui-kit#210]
I want to work on this component next, I have submitted my previous issue,

Here is a reference to the component. 
![Capture3](https://user-images.githubusercontent.com/103353878/196011282-a59b28df-715c-43ab-bd44-ab261575c9fe.PNG)

Kindly assign the issue 

Thank You,
Sayantan

**Comment by yhoungdev** [comment]
can you sign this issue to me ?

**Comment by Rajdip019** [comment]
This is already built. Closing this issue. @SayantanStackflow

**Comment by SayantanStackflow** [comment]
Okay, my bad I guess. I didn't notice the element in the code, I'm trying new one

**Comment by yhoungdev** [comment]
Ok you can assign to Me tho
