### ISSUE TITLE
Create a Feature 

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/web-ui-kit#212]
Hey, I would like to create this Feature card 

### Working ground 
For HTML code - [Tailwind Playgrounds](https://play.tailwindcss.com/) 
For Icon - [Hero Icons](https://heroicons.com/)

### Screenshot 
![Capture](https://user-images.githubusercontent.com/99159580/196016700-b8243d8b-73cb-4ee4-baee-e0e221ba805d.PNG)

Kindly assign it to me So I can raise PR ASAP

Thanks.

**Comment by Rajdip019** [comment]
Go ahead @AKACHI-4
