### ISSUE TITLE
I want to add a simple carousal out of html and css

### ISSUE THREAD

**Issue by JotiradityaB** [Clueless-Community/web-ui-kit#213]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by AashishKatila** [comment]
Could you assign it to me?

**Comment by JotiradityaB** [comment]
I am doing it already

**Comment by Rajdip019** [comment]
I can not see an image here. @AashishKatila
