### ISSUE TITLE
Want to build content card-6

### ISSUE THREAD

**Issue by JotiradityaB** [Clueless-Community/web-ui-kit#218]
![image](https://user-images.githubusercontent.com/114105421/196023186-f067d038-ea00-4877-80ca-8da7d5f372e1.png)

**Comment by Rajdip019** [comment]
This is not in the Figma File. The closing this issue. @JotiradityaB

**Comment by rupsha014** [comment]
@JotiradityaB are u still working on this?

**Comment by AmitDeka** [comment]
@Rajdip019 my PR is already merged . Can you close this

**Comment by AmitDeka** [comment]
Thanks @rupsha014
