### ISSUE TITLE
Create a secondary icon button rounded

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#22]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-29](https://user-images.githubusercontent.com/91758830/195256420-6fe5dbdf-ec17-4e03-a703-de47b39ccc91.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/button_secondary_rounded_icon.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
Please assign to my name

**Comment by Rajdip019** [comment]
You have already I issue assigned. Please make a PR of that to claim another one. @jsvigneshkanna

**Comment by yugalibalbudhe** [comment]
Can you assign this to me? @Rajdip019

**Comment by Rajdip019** [comment]
Sure go ahead @yugalibalbudhe

**Comment by Sneha19-k** [comment]
Could you assign this issue to me @Rajdip019

**Comment by Hiresh23** [comment]
i would like to contribute to this issue

**Comment by Rajdip019** [comment]
I can not see your PR can you link the PR here?

**Comment by yashsarnaik22** [comment]
Can I do this?

**Comment by yugalibalbudhe** [comment]
Hey @Rajdip019 can you see my PR now?

**Comment by Rajdip019** [comment]
Please check the comments @yashsarnaik22 of your PR.

**Comment by Rajdip019** [comment]
Your PR needs change. do that or I will assign this to some one else. @yashsarnaik22

**Comment by MadhurKharche** [comment]
Please allow me to work on this issue

**Comment by rupsha014** [comment]
@yugalibalbudhe  Are u still working on this?

**Comment by Rajdip019** [comment]
Hey any one want to work on this issue then comment below.

**Comment by MadhurKharche** [comment]
Please assign it to me @Rajdip019

**Comment by AdityaShaw1** [comment]
pls assign me i want to contribute in this issue

**Comment by Rajdip019** [comment]
Go ahead @AdityaShaw1

**Comment by AdityaShaw1** [comment]
hlo can u pls tell me , i have to only write the code to make that button and attach a ss of the button ??

**Comment by Rajdip019** [comment]
Yes. Please check the other buttons in the Buttons folder, how the code is written. @AdityaShaw1

**Comment by AmitDeka** [comment]
Hi @Rajdip019  Can you close this issue ?
