### ISSUE TITLE
Create a mobile filter

### ISSUE THREAD

**Issue by nishit3134** [Clueless-Community/web-ui-kit#221]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/111650900/196023619-d09ef317-0c8c-4281-838b-2e1f3713a4ab.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nishit3134** [comment]
@Rajdip019 I would like build this component

**Comment by Rajdip019** [comment]
Go ahead @nishit3134
