### ISSUE TITLE
Create a email form group

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#222]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-1](https://user-images.githubusercontent.com/109761128/196024047-9fa250a7-b01a-4933-a8e8-8b44c5773f8e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form groups/form-groups-email-form-group.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rrsingh11** [comment]
Hey @rupsha014 ! , I would like to work on this issue could you assign it to me?

**Comment by myGlitches** [comment]
@Rajdip019 @rupsha014 , is @rrsingh11 working on this?

**Comment by udoyhasan** [comment]
@rupsha014 @Rajdip019 can I work on this component? I've already created a pull request #260

**Comment by akanshaaa19** [comment]
Please Assign this issue to me.

**Comment by rohan9024** [comment]
@Debajyoti14 @Rajdip019  please assign me

**Comment by rohan9024** [comment]
@Rajdip019 Also, Can you review my previous PR as well?
