### ISSUE TITLE
Want to Create - Alert Red Button 

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/web-ui-kit#223]
Here is a reference to the component. 

Will add it to the Alerts folder

![Error Alert Issue](https://user-images.githubusercontent.com/65249625/196024071-35a1e3a4-7334-43b5-a0bf-c12b2a21f49a.png)

**Comment by Rajdip019** [comment]
Go ahead @myGlitches

**Comment by myGlitches** [comment]
Thanks @Rajdip019

**Comment by myGlitches** [comment]
Done
