### ISSUE TITLE
Create a Feature Card - Choose File 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#224]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-3](https://user-images.githubusercontent.com/91758830/196024098-d1a09d57-6155-4b64-ad68-ae1e4b756b63.png)

On click this should open the file manager.

After building the component please raise a PR with a screenshot of the component and add the component in `Form groups/choose-file.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rrsingh11** [comment]
Hey @Rajdip019 ! I would like to work on this issue. Could you please assign it to me?

**Comment by Rajdip019** [comment]
Sure. go ahead @rrsingh11

**Comment by rrsingh11** [comment]
Hey, @Rajdip019  do you want "Go" to be a button and that icon to select the file from File manager?

**Comment by Rajdip019** [comment]
Hey are you working on this or I can assign any one else in this? @rrsingh11

**Comment by rrsingh11** [comment]
Hey, Sorry I thought you are not an active maintainer because I asked the question and you didn't reply. Sorry my bad.

I took another project, you can assign it to someone else.

**Comment by Rajdip019** [comment]
Hey, this repo is being maintained regularly, somehow I missed this one. Sorry for the inconvenience.

**Comment by rrsingh11** [comment]
No problem. Actually I took another task, after I complete it and no one would be working on it then I would ask you to assign me again.
Thank you

**Comment by jesulonimii** [comment]
Please assign me this
