### ISSUE TITLE
Create a Search filter category 

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#225]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-6](https://user-images.githubusercontent.com/91758830/196024165-d4c445f4-0abf-4895-9be7-78edaa7ad8d5.png)

After building the component please raise a PR with a screenshot of the component and add the component in `From groups/search-filter-category.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SayantanStackflow** [comment]
I'd like to ask you to assign me @Rajdip019 on this component, I'm available right now.

**Comment by Rajdip019** [comment]
I guess you are already assigned to an issue. @SayantanStackflow

**Comment by myGlitches** [comment]
@Rajdip019 Onto this now ~

**Comment by Rajdip019** [comment]
Go ahead @myGlitches

**Comment by SayantanStackflow** [comment]
> I guess you are already assigned to an issue. @SayantanStackflow

ya it's okey I got assigned to another component before you replied

**Comment by myGlitches** [comment]
Done ! @Rajdip019
