### ISSUE TITLE
Create a Search with zip

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#226]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-7](https://user-images.githubusercontent.com/91758830/196024232-6f1e2409-d51a-42b5-af0a-307a30343866.png)

After building the component please raise a PR with a screenshot of the component and add the component in `From groups/search-zip.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rohan9024** [comment]
@Rajdip019 Hey, Can I work on this?

**Comment by Rajdip019** [comment]
Go ahead @rohan9024
