### ISSUE TITLE
Create a search form group-1

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#227]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-4](https://user-images.githubusercontent.com/109761128/196024180-eabd803f-f1b3-437b-94d9-58aafedb35f1.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form groups/form-groups-search-form-group1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by its-kundan** [comment]
!assign

**Comment by Rajdip019** [comment]
not assign you? @its-kundan Ha ha.

**Comment by rohan9024** [comment]
@rupsha014 Can I work on this?

**Comment by its-kundan** [comment]
> not assign you? @its-kundan Ha ha.

bro... its bot command for assign !! 
I guess you are noob,

**Comment by myGlitches** [comment]
@Rajdip019 Assign this to me please! Done with the other 2

**Comment by Rajdip019** [comment]
Okay go for it. @myGlitches

**Comment by myGlitches** [comment]
@Rajdip019 thanks!

**Comment by myGlitches** [comment]
Done!
