### ISSUE TITLE
Create a search version 4

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#228]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-8](https://user-images.githubusercontent.com/91758830/196024276-b0d155cc-cba2-4a9b-8ba4-7533951be49e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `From groups/search-v4.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rohan9024** [comment]
@Rajdip019 Can I work on this?

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @rohan9024 Finish that first

**Comment by rohan9024** [comment]
@Rajdip019 Okay sure

**Comment by SayantanStackflow** [comment]
Hi, @Rajdip019 can I work on this component? Since I'm seeing no one have been assigned on it yet and I have submitted my previous pr.

Thank you,
Sayantan

**Comment by rupsha014** [comment]
@SayantanStackflow go ahead
