### ISSUE TITLE
Create a search form group-2

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#229]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-5](https://user-images.githubusercontent.com/109761128/196024326-3c73434c-4388-4649-bd74-80fa0f8bfda7.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form groups/form-group-search-form-group2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by its-kundan** [comment]
!assign

**Comment by rohan9024** [comment]
@rupsha014 Can I work on this?

**Comment by rupsha014** [comment]
go ahead @its-kundan

**Comment by rupsha014** [comment]
@its-kundan Are u still working on it?

**Comment by rohan9024** [comment]
@rupsha014 assign me if he's not working

**Comment by rohan9024** [comment]
@Rajdip019 assign me this
