### ISSUE TITLE
Create a Secondary button with icon

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#23]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-20](https://user-images.githubusercontent.com/91758830/195256873-48efd8ad-348c-4e5e-8030-ee6cf089217f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/button_secondary_with_icon.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by RajKanani1206** [comment]
I would like to work on it.

**Comment by NizarAhamed97** [comment]
Pls assign me the issue

**Comment by Rajdip019** [comment]
Go ahead @RajKanani1206

**Comment by NizarAhamed97** [comment]
> Go ahead @RajKanani1206

Any other open issue which i can work on?

**Comment by Rajdip019** [comment]
I will be adding more by today. @NizarAhamed97 . Keep looking.
