### ISSUE TITLE
Create a email Form group email-v2

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#230]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-9](https://user-images.githubusercontent.com/91758830/196024328-30bc7102-5d03-479f-80d4-827990cb1e78.png)

After building the component please raise a PR with a screenshot of the component and add the component in `From groups/email-v2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rohan9024** [comment]
@Rajdip019 Can I work on this?

**Comment by Rajdip019** [comment]
Go ahead @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 Alright thank you!
