### ISSUE TITLE
Create a category form group

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#231]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-2](https://user-images.githubusercontent.com/109761128/196024381-812a2b94-f9f8-4433-b782-c2e9151600e0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form groups/form-group-category-form-group.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VSB14** [comment]
Hii Rupsha, can you assign this issue to me?

**Comment by rupsha014** [comment]
go ahead @VSB14
