### ISSUE TITLE
Want to Create - Info Alert 

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/web-ui-kit#233]
Reference to Component 

![Info Alert Notification](https://user-images.githubusercontent.com/65249625/196025367-6b41b431-43a5-4b23-a92e-d5ff498a9bf8.png)

Will add under Alert folder

Good luck.

**Comment by rupsha014** [comment]
@myGlitches go ahead

**Comment by myGlitches** [comment]
Thanks ! @rupsha014

**Comment by myGlitches** [comment]
Done

**Comment by myGlitches** [comment]
Also, @Rajdip019  @rupsha014 is it possible to mention the Figma file and how to contribute, directly in the description for newbies like myself? Can change the doc if you want me to

**Comment by Rajdip019** [comment]
Hey, @myGlitches . We are not giving users to change the Figma file.

**Comment by myGlitches** [comment]
No , I meant something else and I saw it is already mentioned ! My bad sorry ~ hehe
