### ISSUE TITLE
Create a Warning Alert 

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/web-ui-kit#236]
Here is a reference to the component. 

![Warning Alert Notification](https://user-images.githubusercontent.com/65249625/196027237-53a68901-a779-40b6-be6b-f6f0174e0b05.png)

Please Assign

**Comment by Rajdip019** [comment]
Go ahead @myGlitches

**Comment by myGlitches** [comment]
This is done @Rajdip019
