### ISSUE TITLE
Create a Widget List

### ISSUE THREAD

**Issue by infuman69** [Clueless-Community/web-ui-kit#242]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![image](https://user-images.githubusercontent.com/81096719/196028904-0168a8de-38e5-420e-bf01-a39302d0dd22.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by infuman69** [comment]
@Rajdip019 Can I work on this issue?

**Comment by Rajdip019** [comment]
Go ahead. @infuman69

**Comment by rupsha014** [comment]
@infuman69 ...if done with the issue link the PR
