### ISSUE TITLE
Create an Image Card

### ISSUE THREAD

**Issue by om-dhumal** [Clueless-Community/web-ui-kit#243]
Hey, I would like to add an image card with a brief description and explore button. For ref I have attached a gif below.
Tools/ Libraries which I would be using : HTML, Tailwind CSS

Reference to the component
![imageCardm1](https://user-images.githubusercontent.com/94060153/196030278-ee423c71-c3ca-40aa-a5ab-499d090ea624.gif)

**Comment by Rajdip019** [comment]
This is not in the Figma Design. Please choose a UI component from the figma file. @om-dhumal
