### ISSUE TITLE
Create Card Item 22

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/web-ui-kit#250]
Here is a reference to the component that I want to make

![card-item-22](https://user-images.githubusercontent.com/65249625/196037107-d8c61ef8-d64e-4d1b-acda-7140e92c3886.png)

**Comment by myGlitches** [comment]
feature-card-item-22

**Comment by Abhishek3223** [comment]
hey can i do this?

**Comment by AdityaShaw1** [comment]
can u pls assign me
