### ISSUE TITLE
Create a widget list-item-6

### ISSUE THREAD

**Issue by akanshaaa19** [Clueless-Community/web-ui-kit#262]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/76031685/196112274-608221dd-ba44-476b-af97-3c9d34d99074.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Go ahead build it. @akanshaaa19

**Comment by rupsha014** [comment]
@akanshaaa19 if you are done with the issue... please link the PR to the issue

**Comment by rupsha014** [comment]
please comment if anybody else wants to work on this issue
