### ISSUE TITLE
Create a Contact component

### ISSUE THREAD

**Issue by akanshaaa19** [Clueless-Community/web-ui-kit#263]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![image](https://user-images.githubusercontent.com/76031685/196112617-b7dde241-869c-4768-b596-84cb71867c9e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by akanshaaa19** [comment]
Please assign

**Comment by jaswindersingh2601** [comment]
Assign this issue to me, I am interested to work in this issue.

**Comment by Rajdip019** [comment]
This component is already assigned to someone else so closing this issue. @akanshaaa19
