### ISSUE TITLE
Create a  Desktop/ Mobile Filter

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#266]
I would like to create this component-

![image](https://user-images.githubusercontent.com/64919642/196146835-e4fb21f6-3024-46f5-8817-e6580bdf6a55.png)

![image](https://user-images.githubusercontent.com/64919642/196146477-b6b82d7f-e5a6-4318-89bf-6f22b5976a74.png)

Please assign me this.

**Comment by Rajdip019** [comment]
Please choose one @rohan9024 the I will assign you.

**Comment by rohan9024** [comment]
@Rajdip019 Can I create both and make different PRs?

**Comment by Rajdip019** [comment]
Okay sure. Do that. @rohan9024

**Comment by Rajdip019** [comment]
The desktop version is done? @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 yep!

Create marketplace-products.html #270
