### ISSUE TITLE
Create a Upload Input formgroup

### ISSUE THREAD

**Issue by jesulonimii** [Clueless-Community/web-ui-kit#269]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/70331030/196206039-55130974-ea17-45c8-802e-c4b069d40261.png)

After building the component please raise a PR with a screenshot of the component and add the component in `/FormGroups/upload-input.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
hey @jesulonimii this PR is already raised. Assigning that issue to you and closing this one.

**Comment by Rajdip019** [comment]
Comment on #224 Issue I will assign you . @jesulonimii
