### ISSUE TITLE
Create a Mobile Filter

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#272]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/64919642/196209592-d8604b01-f6df-4ff9-bbe5-d75147d97e20.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rohan9024** [comment]
@Rajdip019 please assign this

**Comment by Rajdip019** [comment]
Go ahead @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 done👍
