### ISSUE TITLE
Create a Mobile Nav 2

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#278]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar navbar-light](https://user-images.githubusercontent.com/91758830/196252512-9f193cdf-863a-473b-a23e-05bcfd24f1b1.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav-mobile/nav-2.html`
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by Rajdip019** [comment]
Go ahead. @madmaxWMFU
