### ISSUE TITLE
Create Mobile Nav-5

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#282]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar-style-4 navbar-light](https://user-images.githubusercontent.com/91758830/196253253-e264c456-6414-45d9-ae5d-563b744f006d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav-mobile/nav-5.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by 20RitikSingh** [comment]
I want to contribute to this.

**Comment by Rajdip019** [comment]
Go ahead. @20RitikSingh

**Comment by rupsha014** [comment]
@20RitikSingh are you still working on this issue?

**Comment by rupsha014** [comment]
If anybody else wants to work on this issue then please comment.

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by Viren0602** [comment]
I have raised a PR on issue #282 look over it if you need any changes

**Comment by Viren0602** [comment]
I was assigned with this issue and I have raised a PR for that but my PR was not accepted and the issue is closed.
