### ISSUE TITLE
Create a Product item 4

### ISSUE THREAD

**Issue by MadhurKharche** [Clueless-Community/web-ui-kit#287]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/78757405/196260338-3a0390db-55fe-4d25-8675-aa54a10a6fac.png)

After building the component please raise a PR with a screenshot of the component. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Go ahead @MadhurKharche
