### ISSUE TITLE
Create a Issue and make a component by yourself guide.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#29]
Here is a link to the figma UI kit. [Figma File](https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988)

Take a screenshot of the component you want to build. Make sure the component is not already built.

Then create an issue using the `New Component` issue template. Get assigned and build it.

This is super easy. 👍

**Comment by yashsarnaik22** [comment]
So when I select a component, I have to create a new issue? and then you will assign it to me?

**Comment by Rajdip019** [comment]
Yes @yashsarnaik22

**Comment by aritra-tech** [comment]
@Rajdip019 you can do one thing, which components are done or someone is doing that one so you can mark them as complete it will be easy for the users to see which are done and which are not.

**Comment by myGlitches** [comment]
@Rajdip019 Hi again  , which are the ones already done?

**Comment by Rajdip019** [comment]
Will be updating the Figma File soon. The green marks are done already. @myGlitches

**Comment by myGlitches** [comment]
@Rajdip019 Great , so the form is not done right?

https://prnt.sc/-R4XeaFOIQ2A


This one , will create a request then and delete this comment

**Comment by Rajdip019** [comment]
Yeah raise a issue for them but those will be different different issues. @myGlitches

**Comment by myGlitches** [comment]
Got it ! @Rajdip019

**Comment by prem-io** [comment]
@Rajdip019 A tiny suggestion. Can you also mark the components in the figma file with a different color to indicate if it is already assigned. This will make things little ease for others to pick new issues.

**Comment by Rajdip019** [comment]
The green background components are already built or the Issue is there. We try to update that everyday! @prem-io

**Comment by Sejal-shh** [comment]
Is this issue already been assigned ?
