### ISSUE TITLE
Create Product Card-1

### ISSUE THREAD

**Issue by a-u-m** [Clueless-Community/web-ui-kit#294]
@Rajdip019 I would like to work on the following component
Here is a reference to the component. 
<img width="204" alt="Screenshot 2022-10-18 at 1 10 53 AM" src="https://user-images.githubusercontent.com/115929571/196333020-e0fb04f0-02ad-4d85-927f-10c93e96f6f8.png">

**Comment by Rajdip019** [comment]
Go ahead @a-u-m
