### ISSUE TITLE
Create a Feature Card

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#299]
Here is a reference to the component-

![image](https://user-images.githubusercontent.com/64919642/196370112-e4a20233-1e4a-4632-825f-823d628d9c7e.png)

Please assign this.

**Comment by hritikbhattacharya** [comment]
@Rajdip019 can i work on this

**Comment by rohan9024** [comment]
@hritikbhattacharya already done bruh😎

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
