### ISSUE TITLE
Create a Widgets Item

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#300]
Here is a reference to the component- 

![image](https://user-images.githubusercontent.com/64919642/196370572-67953b44-8dd5-4f68-8130-f7f9654390aa.png)

Please assign this

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 Already created a PR.

**Comment by rohan9024** [comment]
@Rajdip019 yoo here is the component -->

![image](https://user-images.githubusercontent.com/64919642/196491042-68cbefce-41b1-482d-9d6a-634bc01a22a5.png)

**Comment by hritikbhattacharya** [comment]
@Rajdip019 this is not good , he is creating the ui designs without getting assigned

**Comment by rohan9024** [comment]
@hritikbhattacharya because I had completed the previous design

**Comment by hritikbhattacharya** [comment]
@rohan9024 then wait till he assign you the issue

**Comment by rohan9024** [comment]
@hritikbhattacharya whenever he does, I'll be ready with my PR 😎

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
