### ISSUE TITLE
Create a Pagination

### ISSUE THREAD

**Issue by aritra-tech** [Clueless-Community/web-ui-kit#31]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (141)](https://user-images.githubusercontent.com/80090908/195280325-3ae600e5-4af6-49a7-8009-f6d168194f4c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `pagintion/index.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Awesome work on this. @aritra-tech
