### ISSUE TITLE
create a sticky navigation bar

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Clueless-Community/web-ui-kit#312]
## What is the motivation for adding/enhancing this feature?
It will be a simple responsive navigation bar that will be create by myself.

## What are the acceptance criteria?
I would like to do this feature using html,css only.

- [x] ...

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Rajdip019** [comment]
Hey, @Sulagna-Dutta-Roy we are not accepting components from outside the figma file. @Sulagna-Dutta-Roy
