### ISSUE TITLE
Create a email Form 

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#315]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![form-input-14](https://user-images.githubusercontent.com/109761128/196537790-d17feae0-c8d4-4f69-855e-d580f718552a.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-email-form.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Halim-Shams** [comment]
Can you assign this to me

**Comment by Rajdip019** [comment]
Hey You are already assigned to an issue. Please finish that first. @Halim-Shams

**Comment by animesh156** [comment]
@rupsha014  @Rajdip019  can you assign thsi to me

**Comment by Rajdip019** [comment]
Go ahead @animesh156
