### ISSUE TITLE
Create a select option form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#316]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-15](https://user-images.githubusercontent.com/109761128/196538416-56cf1f27-30dd-4b48-90cd-866a85794b58.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-select-option-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Halim-Shams** [comment]
I can do that for you.

**Comment by rohan9024** [comment]
@Rajdip019 @rupsha014 please assign

**Comment by abirhasanohi** [comment]
@Rajdip019 @rupsha014 I've created this component and make a pull request #328

**Comment by rohan9024** [comment]
@abirhasanohi they'll assign you first then only you can make a PR 😂...........aisa toh bhai hum bhi hazaar PR create kar le🤣
