### ISSUE TITLE
Create a search form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#317]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-16](https://user-images.githubusercontent.com/109761128/196539581-9047e227-1850-46ef-abb4-9a05d9367761.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-search-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Halim-Shams** [comment]
can you assign this to me.

**Comment by Rajdip019** [comment]
Go ahead @Halim-Shams
