### ISSUE TITLE
Create a get file form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#318]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-17](https://user-images.githubusercontent.com/109761128/196539997-44cfb22f-6752-46c9-b28b-443a55f79ca7.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-get-file-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by RachitGarg-12** [comment]
@rupsha014  i would like to contribute on this issue.

**Comment by rohan9024** [comment]
@rupsha014 @Rajdip019 please assign

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
