### ISSUE TITLE
Create a notearea-1 form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#319]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-18](https://user-images.githubusercontent.com/109761128/196540349-0fb9abc3-9820-4e17-8c0e-fa0718cab662.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-notearea1-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by RachitGarg-12** [comment]
@rupsha014  i would like to contribute on this issue.

**Comment by rohan9024** [comment]
@Rajdip019 @rupsha014 please assign

**Comment by Rajdip019** [comment]
Go ahead @RachitGarg-12
