### ISSUE TITLE
Create a notearea2 form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#320]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-19](https://user-images.githubusercontent.com/109761128/196540527-f8483f6a-1ece-439a-82f4-c53158239841.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-notearea2-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by udoyhasan** [comment]
@rupsha014 @Rajdip019 I've created a pull request for this component in #323
