### ISSUE TITLE
Create a messagearea form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#321]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-input-20](https://user-images.githubusercontent.com/109761128/196540717-c2ca06af-e32f-4f7d-826a-f6b6849ec70d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/form-messagearea-form.html`. 

  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rodolfonei** [comment]
I would like to work on this one, please

**Comment by Rajdip019** [comment]
Go ahead @rodolfonei

**Comment by DeveVivek** [comment]
Is the issue solved?
