### ISSUE TITLE
Create a pricing-style-2

### ISSUE THREAD

**Issue by Aditya-Shahari** [Clueless-Community/web-ui-kit#333]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![pricing-style-2](https://user-images.githubusercontent.com/90385171/196693611-3a629406-cf4b-4b2a-95f9-793468a313a8.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Pricing Components/pricing-style-2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Aditya-Shahari** [comment]
Hi, I would like to work on this issue, kindly assign it to me

**Comment by Rajdip019** [comment]
Go ahead. @Aditya-Shahari
