### ISSUE TITLE
Create a testimonial-v9 

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#336]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![test9](https://user-images.githubusercontent.com/76204863/196705761-5fcdb94b-7148-4743-9cda-6f8f280f21c0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
This one looks cool. @rahulkarda Go ahead.
