### ISSUE TITLE
Create a footer-v2

### ISSUE THREAD

**Issue by randomrock** [Clueless-Community/web-ui-kit#338]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![footer](https://user-images.githubusercontent.com/73513711/196712782-2cd86f0e-daf1-4245-bcdd-b565310bae0b.PNG)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by itsmanojthapa** [comment]
Hey, can you assign this issue to me?

**Comment by DeveVivek** [comment]
Assign me this issue...!!!
