### ISSUE TITLE
Store buttons component

### ISSUE THREAD

**Issue by preciousjohn** [Clueless-Community/web-ui-kit#34]
One needs to make this component using `HTML` and `Tailwind CSS`. I would suggest using [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="1188" alt="Screen Shot 2022-10-12 at 11 20 39" src="https://user-images.githubusercontent.com/45792786/195304503-6047b917-5977-458f-9b4d-a580c9c5ab77.png">

After building the component, please raise a PR with a screenshot of the component and add the component in the `path of the file`. 
  
If you need to use any icon, please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Hey, @preciousjohn all of these will be made by different different person to give everyone a chance to contribute. Please select any one of the store button to begin with.

**Comment by preciousjohn** [comment]
Alight,
I will work on the Download on the app store button.
Do I need to create an issue for that?

**Comment by Rajdip019** [comment]
We are creating the issue for these store buttons please select one and comment that you want to work. We will assign you. @preciousjohn

**Comment by Rajdip019** [comment]
Closing this issue. @preciousjohn
