### ISSUE TITLE
Create a Widget Items

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#343]
Here is the screenshot -->

![image](https://user-images.githubusercontent.com/64919642/196742496-ccd83741-64c0-4f5c-a3ba-b63ef91efdc8.png)

please assign me

**Comment by Rajdip019** [comment]
Go ahead @rohan9024

**Comment by Saloni2004** [comment]
Hey, could you please assign me this

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
