### ISSUE TITLE
Marketplace product

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/web-ui-kit#347]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![4646](https://user-images.githubusercontent.com/44370586/196780102-a570c845-c29f-4ea0-8aee-575dd3cff7ac.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Go ahead. @hritikbhattacharya

**Comment by hritikbhattacharya** [comment]
@Rajdip019  i want to work on this part
