### ISSUE TITLE
Create a Pricing Style-6 card

### ISSUE THREAD

**Issue by MadhurKharche** [Clueless-Community/web-ui-kit#349]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/78757405/196780918-c2f024f4-b456-4ccf-bb62-cd99160ab11b.png)

After building the component please raise a PR with a screenshot of the component. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by MadhurKharche** [comment]
Please assign this issue to me.

**Comment by Rajdip019** [comment]
Go ahead. @MadhurKharche
