### ISSUE TITLE
Create a Primary table

### ISSUE THREAD

**Issue by its-ayush-07** [Clueless-Community/web-ui-kit#35]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![clweb#2](https://user-images.githubusercontent.com/74665996/195305922-d41c68ea-af77-4e86-a0cb-83fe10f4a615.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Tables/table_primary.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure. Go ahead an d build it. @its-ayush-07
