### ISSUE TITLE
Marketplace product 2

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/web-ui-kit#352]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![737](https://user-images.githubusercontent.com/44370586/196783736-17b70aac-062c-4861-9098-e5f949cc8d10.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by hritikbhattacharya** [comment]
@Rajdip019 i want to work on this issue

**Comment by hritikbhattacharya** [comment]
I am already started working on it , and almost completed it.

**Comment by hritikbhattacharya** [comment]
@Iam-SilentEyes  you can work on its next part (size part ) which is similar to this

**Comment by Rajdip019** [comment]
Go ahead @hritikbhattacharya
