### ISSUE TITLE
Create From Large Search with Zip

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#353]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-4](https://user-images.githubusercontent.com/91758830/196790676-d9b4cbc8-a1d4-48bb-bd8f-e30738f2312f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/search-zip-large.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Iam-SilentEyes** [comment]
Can you assign me to this

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @Iam-SilentEyes

**Comment by bbsdevloper** [comment]
Hey @Rajdip019 
I have solved my previous issue which is is assigned to me can you please assign this to me as well .

**Comment by rupsha014** [comment]
@Iam-SilentEyes are you still working on this?

**Comment by bbsdevloper** [comment]
Yes i have just posted the PR check please
