### ISSUE TITLE
Create Email with button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#354]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-5](https://user-images.githubusercontent.com/91758830/196791105-eaef8a74-2fef-4bba-b209-b9290c78817b.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/email-with-button-large.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Iam-SilentEyes** [comment]
Can you assign me to this

**Comment by Rajdip019** [comment]
Go ahead @Iam-SilentEyes

**Comment by Rajdip019** [comment]
Hey, @Iam-SilentEyes are you still working on this?

**Comment by Iam-SilentEyes** [comment]
Yeah I'm working on this
