### ISSUE TITLE
Create Search with category large

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#355]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-8](https://user-images.githubusercontent.com/91758830/196791397-2403575b-6de7-4cef-9af6-63cd11945486.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/search-category-large.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by DarioCostaAlves** [comment]
Can you assign to me? Thanks

**Comment by Rajdip019** [comment]
Go ahead @DarioCostaAlves

**Comment by rupsha014** [comment]
@DarioCostaAlves are you still working on this?

**Comment by DarioCostaAlves** [comment]
> @DarioCostaAlves are you still working on this?

Yes, I will build this component when I leave the work.
