### ISSUE TITLE
Create Message box large

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#356]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![form-group-6](https://user-images.githubusercontent.com/91758830/196791838-69536c88-15a0-4c1d-96fb-79ecc75fa7bb.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/message-box-large.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by CodeRyliCode** [comment]
Could you assign me to this? 

Here's my PR for this issue:[https://github.com/Clueless-Community/web-ui-kit/pull/363]( https://github.com/Clueless-Community/web-ui-kit/pull/363)

**Comment by Rajdip019** [comment]
Okay will check that. @CodeRyliCode
