### ISSUE TITLE
Create a email large form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#357]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![form-group-1](https://user-images.githubusercontent.com/109761128/196792088-071b3ce2-a97e-45cc-b51f-d5a018af4473.png)

After building the component please raise a PR with a screenshot of the component and add the component in `form/form-email-large-form.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by mnkyjs** [comment]
Hello @rupsha014, can you please assign me for this issue as well please? 😊

**Comment by bbsdevloper** [comment]
Hello @rupsha014 
I want to work on this issue.
please assign this to me

**Comment by Michelle031** [comment]
Can I please be assigned this issue, I will deliver quickly. Thank you

**Comment by Rajdip019** [comment]
Hey, @Michelle031 go ahead.

**Comment by AmitDeka** [comment]
@Rajdip019 can you close this issue
