### ISSUE TITLE
Create a file large form

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#359]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-7](https://user-images.githubusercontent.com/109761128/196792704-07d8c2e3-41ba-4c84-9cae-e9ec8c53e9b7.png)

After building the component please raise a PR with a screenshot of the component and add the component in `forms/form-file-large-form.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by mnkyjs** [comment]
Hello @rupsha014, can you please assign me for this ticket? ❤️ 😊

**Comment by Rajdip019** [comment]
Go ahead @mnkyjs

**Comment by mnkyjs** [comment]
Done @Rajdip019 😊

https://github.com/Clueless-Community/web-ui-kit/pull/443
