### ISSUE TITLE
Create a store button for apple 

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#36]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![Market button](https://user-images.githubusercontent.com/109761128/195309468-bc21b3c6-11e4-4010-95c9-6f997f2fe315.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-for-apple-lightmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by Rajdip019** [comment]
You are already assigned in an issue. Will be assigning you another one when it's finished. @madmaxWMFU

**Comment by Rajdip019** [comment]
Go ahead @preciousjohn

**Comment by Hiresh23** [comment]
i would like to work on this issue ,please assign
