### ISSUE TITLE
Create a search large form -2

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#361]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![form-group-3](https://user-images.githubusercontent.com/109761128/196793382-6d6a6caa-921c-4d78-b777-f7b5c2f5c0b0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `form/form-search-large-form2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Upasana-Roy** [comment]
Can you please assign it to me. I want to work on this

**Comment by rupsha014** [comment]
@Upasana-Roy go ahead
