### ISSUE TITLE
Create a Statistics component

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#364]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![stats](https://user-images.githubusercontent.com/76204863/196850705-2b9c2d58-f4a2-47cb-b37e-aa12cac02324.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Looks go also will review the PR. @rahulkarda
