### ISSUE TITLE
marketplace product 3 

### ISSUE THREAD

**Issue by hritikbhattacharya** [Clueless-Community/web-ui-kit#369]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![1](https://user-images.githubusercontent.com/44370586/196855771-f03ed9d8-b5c1-40e9-9c3b-5c7dafb3f5cd.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by hritikbhattacharya** [comment]
@Rajdip019 @rupsha014  I want to work on this portion

**Comment by DeveVivek** [comment]
Please assign me this portion.
