### ISSUE TITLE
Create a store button for google play

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#37]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![Market button (1)](https://user-images.githubusercontent.com/109761128/195311364-55129942-10af-45d3-9ea5-a960bb6c33b3.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-googleplay-lightmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure go ahead. @kartikjoshi267

**Comment by Rajdip019** [comment]
Yes you can use font awesome CDM link and you need to create a new file as per the instructions inside the Store Button folder. @kartikjoshi267
