### ISSUE TITLE
Create a Footer 12 white

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#374]
Here is a reference to the component-->

![image](https://user-images.githubusercontent.com/64919642/196928299-80ecb103-51cc-4054-a977-ef0e64777633.png)

Please assign me.

I have also created a PR ....please review my PR.

**Comment by Rajdip019** [comment]
Go ahead @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
