### ISSUE TITLE
Create a Profile Card

### ISSUE THREAD

**Issue by itsmanojthapa** [Clueless-Community/web-ui-kit#375]
Here is a reference to the component

![image](https://user-images.githubusercontent.com/109368904/196932412-cc6a0491-b318-4eee-b938-88f6252fecb4.png)

assign me for this component.

**Comment by avezqureshi14** [comment]
can you assign me

**Comment by avezqureshi14** [comment]
Hey @itsmanojthapa bro can you assign this to me

**Comment by itsmanojthapa** [comment]
@avezqureshi14  i am not a maintainer of this project.

**Comment by Rajdip019** [comment]
This is not in the Figma File. Please read the docs to before raising an issue. @itsmanojthapa
