### ISSUE TITLE
Create a Footer 12 dark 

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#378]
Here is a reference to the component -->

![image](https://user-images.githubusercontent.com/64919642/196934659-7d8de4ca-a642-4e55-9bf9-16c4653ad086.png)

Please assign me I have already created this component

**Comment by avezqureshi14** [comment]
can you assign this to me

**Comment by rohan9024** [comment]
@avezqureshi14 I have already created this component.... If you want to get assigned then look for the figma file and choose any component and create issue 👍

**Comment by rohan9024** [comment]
#382

**Comment by rohan9024** [comment]
@Rajdip019 done 👍
