### ISSUE TITLE
Create a Footer 11 white 

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#384]
Here is a reference to the component-->

![image](https://user-images.githubusercontent.com/64919642/196967777-c56798b2-9294-46c0-9c52-823f51fa4a12.png)

Please assign me

**Comment by Rajdip019** [comment]
Bro slow down haha. Give other chance as well. @rohan9024

**Comment by rohan9024** [comment]
@Rajdip019 yeah yeah 😂......took a day off!
