### ISSUE TITLE
Create a Navbar 6

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/web-ui-kit#391]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/99157367/197047346-52db51a9-9584-4984-ad7a-fbe949cf82a0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `navbar_6.html. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
Can you assign this to me @Rajdip019

**Comment by Rajdip019** [comment]
Go ahead.
