### ISSUE TITLE
Create a Navbar 15

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/web-ui-kit#397]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/99157367/197057712-ad123e59-17b2-4a93-bbd1-72899c723045.png)
After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
Hey @Rajdip019 
i want to work on this UI to Tailwind Css code conversion

**Comment by Rajdip019** [comment]
You are already assigned to two issues. Please finish them first. @bbsdevloper

**Comment by bbsdevloper** [comment]
@Rajdip019  brother pls don't assign these issue created by me to anyone because i have already coded all the UI's
I am just waiting for PR got merged

**Comment by saimaheshtaduri** [comment]
@Rajdip019 please assign this to me if possible.

**Comment by Hiresh007** [comment]
Please assign me this
