### ISSUE TITLE
Create a button with icon

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#4]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![btn-sm-2](https://user-images.githubusercontent.com/109761128/195183835-52b32ef4-e0b8-4c39-be56-c5bda6eefeba.png)
 

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/button_with_icon.html`. 

Good luck.

**Comment by ElectricPlant19** [comment]
can you assign it to me ?

**Comment by Rajdip019** [comment]
Please go ahead! @ElectricPlant19

**Comment by Rajdip019** [comment]
Use icons from here. [Hero Icons](https://heroicons.com/) @ElectricPlant19

**Comment by Hiresh23** [comment]
i would like to contribute
