### ISSUE TITLE
Create a store button for windows

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#40]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![Market button (4)](https://user-images.githubusercontent.com/109761128/195314267-00448189-5b29-4603-9cb5-4585902770c2.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-windows-lightmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure. @madmaxWMFU

**Comment by rupsha014** [comment]
issue resolved
