### ISSUE TITLE
Create a Team component

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#400]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![team](https://user-images.githubusercontent.com/76204863/197104606-112cb453-aba5-45a2-a96b-ad1855742a27.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Please choose a template from Figma added lots of more UI components. @rahulkarda

**Comment by rahulkarda** [comment]
> Please choose a template from Figma added lots of more UI components. @rahulkarda

I lost the link, send it again please!
