### ISSUE TITLE
Create a store button for apple darkmode

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#41]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![Market button (3)](https://user-images.githubusercontent.com/109761128/195316002-ceeab8fc-4692-49ff-9797-168d869042e5.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-apple-darkmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by error707-persona** [comment]
I would like to work on this, please assign it to me

**Comment by Rajdip019** [comment]
@error707-persona you are already assigned to an issue. @Hiresh23 work on this one.

**Comment by Hiresh23** [comment]
i have added the button check please
