### ISSUE TITLE
Create a footer 3 white

### ISSUE THREAD

**Issue by rakicodes** [Clueless-Community/web-ui-kit#412]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="865" alt="Screen Shot 2022-10-21 at 10 19 30 AM" src="https://user-images.githubusercontent.com/101219940/197243993-874ae74b-3c2f-4ef0-9fd5-cfa7bd752a87.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rakicodes** [comment]
I would like to work on this

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?
