### ISSUE TITLE
Create a Avatar component

### ISSUE THREAD

**Issue by prem-io** [Clueless-Community/web-ui-kit#414]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

<img width="1112" alt="Screenshot 2022-10-21 at 11 11 02 PM" src="https://user-images.githubusercontent.com/51167082/197262330-8e0ad14a-a12c-455d-9f95-5b636456054e.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by prem-io** [comment]
Hey @Rajdip019 @rupsha014, I want to work on this component. Kindly, assign this to me.

**Comment by prem-io** [comment]
@rupsha014 Could you please assign this to me.

**Comment by Rajdip019** [comment]
This looks good @prem-io work on this.

**Comment by prem-io** [comment]
@Rajdip019 @rupsha014 Raised [PR](https://github.com/Clueless-Community/web-ui-kit/pull/440) for this issue. Kindly, review and comment if any changes required.
