### ISSUE TITLE
Create Navbar-13

### ISSUE THREAD

**Issue by Ruchita1010** [Clueless-Community/web-ui-kit#415]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (317)](https://user-images.githubusercontent.com/70577616/197264452-6ac30fbc-e36b-43d3-985f-6ab4dd8a6f75.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Ruchita1010** [comment]
Can I get assigned to this issue?

**Comment by bbsdevloper** [comment]
Please assign this issue i have cdeded it

Here is the screenshot
![image](https://user-images.githubusercontent.com/99157367/197322170-97b63dac-be01-46cb-ba4e-3e6abcc43c5a.png)

**Comment by Ruchita1010** [comment]
@Rajdip019 Aren't we supposed to get assigned first and then work on the issue?

**Comment by Rajdip019** [comment]
Yeah @Ruchita1010 . Go ahead work on this. @bbsdevloper's PR will get marked invalid if he raises a PR for this. You need to get assigned first.

**Comment by Ruchita1010** [comment]
Thank you!! I will start working on this :)
