### ISSUE TITLE
Create a footer blue -1

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#419]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
<img width="1440" alt="Footer 5 Lift blue" src="https://user-images.githubusercontent.com/109761128/197279492-97fe08c5-9589-4854-a034-dec392443b93.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-blue1.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
Assign it to me
@rupsha014 
@Rajdip019

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?
