### ISSUE TITLE
Create a store button for google play darkmode

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#42]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![Market button (5)](https://user-images.githubusercontent.com/109761128/195316756-58698059-5490-46c3-9f6d-8f5c49e711d1.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-googleplay-darkmode.html`. 
  

If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Hiresh23** [comment]
i would like to work on this issue ,please assign it to me

**Comment by Rajdip019** [comment]
You both are already assigned to an issue please complete them and then only you will get assigned to other issues. @error707-persona @Hiresh23

**Comment by error707-persona** [comment]
I completed the one previously assigned to me please if its I will work on this one too

**Comment by jsvigneshkanna** [comment]
@Rajdip019 , I completed my last PR, please assign me this task

**Comment by Rajdip019** [comment]
Work on it. @error707-persona

**Comment by rupsha014** [comment]
this issue is resolved
