### ISSUE TITLE
Create a footer blue -3

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#425]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
<img width="1440" alt="Footer 7 lift blue" src="https://user-images.githubusercontent.com/109761128/197278079-48ddc772-2e7d-445f-8418-b98498279384.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-blue3.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
Hey @rupsha014 i want to work on this

**Comment by Viren0602** [comment]
Hello sir can you assign this issue to me?

**Comment by Viren0602** [comment]
Sir I have made a PR regarding #425 look if you need any changes
