### ISSUE TITLE
Create a store button for Amazon darkmode

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#43]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### ![Market button (6)](https://user-images.githubusercontent.com/109761128/195317306-6b095c15-c572-4d67-b6db-e74521a699a9.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-amazon-darkmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by error707-persona** [comment]
Hi I would like to work on this please assign it to me

**Comment by error707-persona** [comment]
also, i would like to know if I just have to make the button or do I include it in some other file ?

**Comment by Rajdip019** [comment]
Hey @error707-persona work on this. You just need to create the button file in Tailwind playground and paste the code here. 

That's it.

**Comment by error707-persona** [comment]
ok
