### ISSUE TITLE
Create a Accordion

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#432]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![acc](https://user-images.githubusercontent.com/76204863/197320396-3430dd80-bb24-40e1-817c-da9a7f8434e2.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by prem-io** [comment]
Hey @Rajdip019 @rupsha014, I want to work on this component. Kindly, assign this to me.

**Comment by rupsha014** [comment]
@rahulkarda go ahead
