### ISSUE TITLE
Create a store buttton for windows darkmode

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#44]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
![Market button (7)](https://user-images.githubusercontent.com/109761128/195317887-ef24a54e-79f8-4b1d-aea3-a9f3bec352db.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Button/store-button-windows-darkmode.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Anuran12** [comment]
Hi @rupsha014 i would like to work on this. Assign this to me.

**Comment by Rajdip019** [comment]
Go ahead work on this. @Anuran12

**Comment by Anuran12** [comment]
@Rajdip019  

![image](https://user-images.githubusercontent.com/104062485/195556825-d4dcd0a3-5260-40e3-8595-f7aed5f08888.png)


Is it looking good ?
