### ISSUE TITLE
Create a Footer 11 dark

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#448]
Here is a reference to the component -->

![image](https://user-images.githubusercontent.com/64919642/197345496-d919e676-16cb-4927-8f16-a80bb5b54f64.png)

Please assign me.

**Comment by Visbhavesh** [comment]
Hey @rohan9024  assign it to me

**Comment by shahGnp** [comment]
Can you assign me this please

**Comment by rohan9024** [comment]
@shahGnp @Visbhavesh Already created a PR !
