### ISSUE TITLE
create a more button

### ISSUE THREAD

**Issue by nishit3134** [Clueless-Community/web-ui-kit#46]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![more](https://user-images.githubusercontent.com/111650900/195330772-f26ee222-07a8-4c6d-af90-b47fd013100c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nishit3134** [comment]
@Rajdip019 I would like to work on this component

**Comment by Rajdip019** [comment]
Go ahead @nishit3134

**Comment by rupsha014** [comment]
issue is resolved
