### ISSUE TITLE
Create a navbar-20

### ISSUE THREAD

**Issue by abhijain2003** [Clueless-Community/web-ui-kit#475]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)
![Screenshot 2022-10-24 143718](https://user-images.githubusercontent.com/91718608/197489807-da89c393-2886-4dcf-a3dc-8cbcc7c270a9.png)

Good luck.

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by abhijain2003** [comment]
hey I have raised this issue, let contributor assign this to me please

**Comment by Rajdip019** [comment]
Go ahead @abhijain2003

**Comment by abhijain2003** [comment]
hey why did you close it before merging
