### ISSUE TITLE
Create navbar-8

### ISSUE THREAD

**Issue by Aditya-Shahari** [Clueless-Community/web-ui-kit#480]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar-figma](https://user-images.githubusercontent.com/90385171/197537808-f426bf18-9bda-4d03-90ed-5844a2ccbae4.png) 

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Aditya-Shahari** [comment]
I have already created pr!

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?

**Comment by Keerthivardhan1** [comment]
Aditya-Shahari had already done it right

**Comment by Aditya-Shahari** [comment]
@Rajdip019 I have already created pr please look into it.
