### ISSUE TITLE
Create a navbar-9

### ISSUE THREAD

**Issue by Aditya-Shahari** [Clueless-Community/web-ui-kit#490]
Here is a reference to the component. 
![navbar-9](https://user-images.githubusercontent.com/90385171/197695855-dfb78f49-1d83-45f9-be82-22f0da544d2a.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

**Comment by Aditya-Shahari** [comment]
Hi, I would like to work on this issue, kindly assign it to me

**Comment by avezqureshi14** [comment]
Hey can you assign me this

**Comment by riddhitech** [comment]
Please assign me this issue.
