### ISSUE TITLE
Create a Content card item-5

### ISSUE THREAD

**Issue by akanshaaa19** [Clueless-Community/web-ui-kit#497]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
####![image](https://user-images.githubusercontent.com/76031685/197749567-4818e44a-4c0e-44cd-b3bf-95a440b62865.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by akanshaaa19** [comment]
Please assign

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @akanshaaa19

**Comment by avezqureshi14** [comment]
Hey bro can you assign this to me @Rajdip019

**Comment by Rajdip019** [comment]
Go ahead @avezqureshi14

**Comment by avezqureshi14** [comment]
Bro @Rajdip019 , I had made the pull request please review it and merge it
