### ISSUE TITLE
Create a Accordion v2

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#499]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![acc2](https://user-images.githubusercontent.com/76204863/197751404-bb6b573e-be16-4ea6-989f-e833bdf33a67.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by avezqureshi14** [comment]
Hey can you assign this to me
