### ISSUE TITLE
Create a review card

### ISSUE THREAD

**Issue by yashsarnaik22** [Clueless-Community/web-ui-kit#50]
![Screenshot 2022-10-12 175106](https://user-images.githubusercontent.com/86489787/195341410-97789c38-7098-4ba3-b8fc-01cb5471fa0d.png)
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by yashsarnaik22** [comment]
@Rajdip019 can I create this component?

**Comment by deek121477** [comment]
Can I work on this issue?

**Comment by Rajdip019** [comment]
Sure go ahead @yashsarnaik22

**Comment by Rajdip019** [comment]
This will go inside `Testimonials/basic-testimonial-card.html` @yashsarnaik22

**Comment by yashsarnaik22** [comment]
okay sorry, i put it Cards folder.
Should I push a new PR through testimonials?

**Comment by Rajdip019** [comment]
See the comment in your PR @yashsarnaik22

**Comment by hritikbhattacharya** [comment]
@Rajdip019 you just have have closed my PR regarding this issue

**Comment by hritikbhattacharya** [comment]
assign this issue to me i have already created this card, and apart from that , i have almost created all the UI templates given in figma file for (feature cards) but all my PRs are rejected why ?

**Comment by Rajdip019** [comment]
This is assigned to @yashsarnaik22 then why are you raising a PR against it? @hritikbhattacharya

**Comment by hritikbhattacharya** [comment]
but in last comment it was written one can try to make. that's why i thought it was open

**Comment by hritikbhattacharya** [comment]
but apart from any issue can i contribute?

**Comment by Rajdip019** [comment]
Is this issue resolved? @yashsarnaik22
