### ISSUE TITLE
Create a footer white -15

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/web-ui-kit#502]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### 
<img width="1440" alt="Footer 15 white" src="https://user-images.githubusercontent.com/109761128/197776531-04788888-555e-4332-83f0-8e57ee6c30aa.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-white-15.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rancho2002** [comment]
I would like to work @rupsha014 @Rajdip019

**Comment by TannisthaBiswas** [comment]
Please assign me

**Comment by Rajdip019** [comment]
Go ahead @TannisthaBiswas

**Comment by TannisthaBiswas** [comment]
Created pr #608
