### ISSUE TITLE
Create a Accordion v3

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#545]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![acc3](https://user-images.githubusercontent.com/76204863/198198476-579834c9-baa4-4c29-98aa-6962149e60eb.png)

without rounded borders and background color

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
You have already built it right?

**Comment by rahulkarda** [comment]
> You have already built it right?

This one's without rounded border and background color

**Comment by Rajdip019** [comment]
Okay got it. Will review your PR soon. @rahulkarda
