### ISSUE TITLE
Create a Carousel using html and css(tailwind css)

### ISSUE THREAD

**Issue by abhijain2003** [Clueless-Community/web-ui-kit#55]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](![Screenshot 2022-10-12 183832](https://user-images.githubusercontent.com/91718608/195350468-c18730d0-4bc3-4a64-a061-aa6e5d5bbdeb.png)) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

please assign this to me under hacktoberfest 2022

**Comment by Rajdip019** [comment]
The testimonial is in the Figma File right? @abhijain2003

**Comment by abhijain2003** [comment]
ya but this is just a template, as this repo is web UI kit component, i am trying to develop a carousel using HTML and tailwind CSS 

can you assign it to me

**Comment by rupsha014** [comment]
go ahead @abhijain2003

**Comment by abhijain2003** [comment]
thanks

**Comment by Rajdip019** [comment]
Will you work on this or should I close this issue? @abhijain2003

**Comment by Rajdip019** [comment]
Hey @abhijain2003 ?

**Comment by abhijain2003** [comment]
nope this is not in figma file

**Comment by Rajdip019** [comment]
Closing this PR.
