### ISSUE TITLE
Footer 1 dark.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/web-ui-kit#553]
One needs to make this component using `HTML` and `Tailwind CSS`. I would suggest using [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/93156825/198283397-31345166-3f5c-482e-a59d-099a64f813f8.png)

After building the component please raise a PR with a screenshot of the component and add the component in the `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by divisha6** [comment]
hey @Rajdip019, I am interested in this particular issue. Kindly assign it to me!
