### ISSUE TITLE
Create a Footer Blue 10

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#559]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="1440" alt="Footer 10 Lift blue" src="https://user-images.githubusercontent.com/91758830/198382617-ed4d6e5c-a4ac-4aff-bbf4-ac6b496e6ffc.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-blue-10.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Mayureshkaulwar** [comment]
assign to me
