### ISSUE TITLE
Create a Footer Dark 10

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#562]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="1440" alt="Footer 10 Dark" src="https://user-images.githubusercontent.com/91758830/198382804-7b75503d-04e3-4d30-8dc4-8cf9f73c0ed6.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-dark-10.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Mayureshkaulwar** [comment]
assign to me

**Comment by PrakashGatiyala** [comment]
Hi @Rajdip019  I already have code for it.  Can I create PR for it.

**Comment by PrakashGatiyala** [comment]
Hi @Rajdip019  I have created PR for it. Please check https://github.com/Clueless-Community/web-ui-kit/pull/588
