### ISSUE TITLE
Create a Footer 10 White

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#565]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="1440" alt="Footer 10 white" src="https://user-images.githubusercontent.com/91758830/198383257-5558428d-a414-4401-b5ce-7b86e011a7b2.png">

After building the component please raise a PR with a screenshot of the component and add the component in `Footer/footer-white-10.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Mayureshkaulwar** [comment]
assign to me

**Comment by divyanshusahu** [comment]
I would like to work on this

**Comment by Rajdip019** [comment]
Go ahead @divyanshusahu

**Comment by divyanshusahu** [comment]
@Rajdip019 Please check #578

**Comment by Rajdip019** [comment]
Done @divyanshusahu . You want to get assigned to any other issue please comment there.
