### ISSUE TITLE
Create a Feedback Form

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#57]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![feedback](https://user-images.githubusercontent.com/76204863/195362204-b38d6e7c-9042-486f-93c3-cea977aea864.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by syprogrammer** [comment]
can I take this task

**Comment by rahulkarda** [comment]
> can I take this task

I'm already working on this issue.

**Comment by rahulkarda** [comment]
@Rajdip019 you forgot to close this issue, PR has already been merged.

**Comment by Rajdip019** [comment]
Yeah closing this issue.
