### ISSUE TITLE
Create a Avatar with status indicator

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#576]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![avatarstatus](https://user-images.githubusercontent.com/76204863/198520705-638f7fad-056d-4e94-ad87-d3caa09bb7b0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by AniqJaved** [comment]
I would like to work on this issue

**Comment by rahulkarda** [comment]
> I would like to work on this issue

I've already created a PR for it.
