### ISSUE TITLE
Create a Badge

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#579]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![badges](https://user-images.githubusercontent.com/76204863/198546431-0e69de18-5d8c-427c-ad58-93e92ccfb5c3.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Priyanshu-su30** [comment]
pls assign me this task

**Comment by rahulkarda** [comment]
> pls assign me this task

I've already created a PR for it.
