### ISSUE TITLE
Create a Book appoinment component

### ISSUE THREAD

**Issue by Rancho2002** [Clueless-Community/web-ui-kit#58]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/92109154/195367632-e3d11477-6a74-416f-83d1-35c29a24915b.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by divyamojas** [comment]
Hey @Rancho2002 Please assign me this issue. I would like to work on it.

**Comment by rupsha014** [comment]
please go ahead @divyamojas

**Comment by Rancho2002** [comment]
> please go ahead @divyamojas

I ask for it?

**Comment by Rancho2002** [comment]
> please go ahead @divyamojas

I opened the issue. Why it is assigned to someone else @rupsha014 ?

**Comment by rupsha014** [comment]
sry for miscommunication......@Rancho2002 please go ahead

**Comment by Rancho2002** [comment]
> sry for miscommunication......@Rancho2002 please go ahead

No problem, I am already working on it.
