### ISSUE TITLE
Create a badge v3 (Count indicator)

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#586]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![badgenum](https://user-images.githubusercontent.com/76204863/198567568-63125385-3993-493c-a174-5006fec8e57f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by PrakashGatiyala** [comment]
Hi @rahulkarda I want to work on this issue. Can you assign it to me?

**Comment by PrakashGatiyala** [comment]
Hi @Rajdip019 In Which folder I have to add code?
