### ISSUE TITLE
Create a Nav-18

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#596]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar 18](https://user-images.githubusercontent.com/91758830/198708937-787ca5e7-988d-4d76-a055-2ae6eb360466.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/nav-18.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Mayureshkaulwar** [comment]
Assign to me

**Comment by issue31** [comment]
Please assign this issue to me.

**Comment by Iam-SilentEyes** [comment]
Added pull request
