### ISSUE TITLE
Make resources readme

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#6]
This is a very beginner friendly repo. So the main goal is everyone can contribute here.

If he is lacking anything he can get those skills and then contribute.

So we need to make a `Tutorial.md` file. Where we will have.

- Git and GitHub basics ( Where to study and kunal's  YT video on git and GitHub)
- HTML CSS beginner friendly videos and docs.
- What is tailwind CSS? 
- Link to it's docs
- YT video for tailwind CSS

**Comment by Rajdip019** [comment]
Sure. @sfrunza13

**Comment by sfrunza13** [comment]
@Rajdip019 could you please link me Kunal's YT video on the topic of git and GitHub to include in the Tutorial page

**Comment by Rajdip019** [comment]
Here it is [Link](https://www.youtube.com/watch?v=apGV9Kg7ics&t)

**Comment by SamagraAg** [comment]
Can I do this?
