### ISSUE TITLE
Create a dropdown v3

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#606]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![dropdownplace](https://user-images.githubusercontent.com/76204863/198825313-e37c06f6-4a48-4141-97f7-815c5706ae94.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by yes-im-harsh** [comment]
Assign this to me @rahulkarda

**Comment by rahulkarda** [comment]
> Assign this to me @rahulkarda

I've already created a PR
