### ISSUE TITLE
Create a Rating

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#614]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![rating](https://user-images.githubusercontent.com/76204863/198860116-23417135-403d-4cd5-b487-fd05a2189b58.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Iam-SilentEyes** [comment]
Assign me to this
