### ISSUE TITLE
Create a marketplace product desktop filter 5

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/web-ui-kit#616]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/99157367/198861743-ccca03f0-2dd6-49ef-aae9-b3563e224561.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
Assign me @Rajdip019

**Comment by Rajdip019** [comment]
Go ahead @bbsdevloper

**Comment by Iam-SilentEyes** [comment]
Hey I made it already

**Comment by bbsdevloper** [comment]
> Hey I made it already

Its not the contribution rule brother
first you need to assign 
Am i right @Rajdip019 
By the way i have raised the PR for this
https://github.com/Clueless-Community/web-ui-kit/pull/618

**Comment by Rajdip019** [comment]
Only your PR will get accepted @bbsdevloper . No worries.
