### ISSUE TITLE
Create a Rating v2

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#619]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![rating-text](https://user-images.githubusercontent.com/76204863/198866187-1df938ed-ca4a-4cac-9f2b-ed9d084713e9.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Sejal-shh** [comment]
please assign this to me

**Comment by rahulkarda** [comment]
> please assign this to me

I've already created a PR
