### ISSUE TITLE
Create a Content  Card

### ISSUE THREAD

**Issue by rohan9024** [Clueless-Community/web-ui-kit#624]
Here is a reference to the component-->

![image](https://user-images.githubusercontent.com/64919642/198957121-37b761ba-8e89-4c86-af94-8be0f1cc6b06.png)

I have created a PR as well.

**Comment by Iam-SilentEyes** [comment]
Assign me to this

**Comment by rohan9024** [comment]
@Iam-SilentEyes Already created PR!
