### ISSUE TITLE
Create a select form

### ISSUE THREAD

**Issue by bbsdevloper** [Clueless-Community/web-ui-kit#636]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/99157367/199053858-1b40b3b2-d2fd-4f33-9350-07d0b753e4ff.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bbsdevloper** [comment]
@Rajdip019 assign me

**Comment by Rajdip019** [comment]
This is already built @bbsdevloper
