### ISSUE TITLE
Create a bell notification

### ISSUE THREAD

**Issue by Ruchita1010** [Clueless-Community/web-ui-kit#65]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component.
![Screenshot (279)](https://user-images.githubusercontent.com/70577616/195405353-afb6c087-53ce-44a6-9fcf-b69bab8792cc.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Ruchita1010** [comment]
I would like to work on this issue!

**Comment by rupsha014** [comment]
please go ahead @Ruchita1010
