### ISSUE TITLE
Make a thanks to contributors section in README.md

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#7]
This should include the user's profile picture on clicking that picture we can visit his/her profile.

**Comment by sfrunza13** [comment]
Hi, can I give this a go?

**Comment by SubhamChoudhury** [comment]
Hi @Rajdip019, can you assign me this issue?

**Comment by Soumya-Kushwaha** [comment]
I would like to work on this, please.

**Comment by Rajdip019** [comment]
Hey, @SubhamChoudhury you are already assigned to an issue. So giving this one to @Soumya-Kushwaha

**Comment by Rajdip019** [comment]
Hey @Soumya-Kushwaha are you working on it?

**Comment by Soumya-Kushwaha** [comment]
I tried to search a lot. But does this require NOT AUTOMATIC addition of contributors profile to readme?
Because for automatic addition, I could only find regarding adding contributors section which puts their profile picture tha IS NOT linked to their profiles.
Kindly help me out.

**Comment by Rajdip019** [comment]
That will work. The automated one. You can put that in. @Soumya-Kushwaha
