### ISSUE TITLE
Create a Content Card

### ISSUE THREAD

**Issue by aritra-tech** [Clueless-Community/web-ui-kit#70]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (147)](https://user-images.githubusercontent.com/80090908/195433176-f181f075-ad99-4031-9312-22e8d2d1ede1.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Content Cards/index.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
This issue is solved so closing this.
