### ISSUE TITLE
Create a Testimonial

### ISSUE THREAD

**Issue by aritra-tech** [Clueless-Community/web-ui-kit#71]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/80090908/195434262-452942c6-8e69-4046-9959-f5adda59f179.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/index.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by rupsha014** [comment]
you have already been assingned an issue.....please solve it first @aritra-tech

**Comment by rupsha014** [comment]
go ahead @madmaxWMFU

**Comment by aritra-tech** [comment]
> you have already been assingned an issue.....please solve it first @aritra-tech

Ok ok

**Comment by Rajdip019** [comment]
This Issue is resolved, so closing this issue.
