### ISSUE TITLE
Create a Footer with Copyright & social media handles

### ISSUE THREAD

**Issue by rahulkarda** [Clueless-Community/web-ui-kit#74]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![footer-clueless](https://user-images.githubusercontent.com/76204863/195501869-d45a83c4-9482-4a08-ab6c-032c06a600fe.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by jsvigneshkanna** [comment]
Please assign me this issue, will raise a pr

**Comment by Rajdip019** [comment]
Hey this is not in the figma file, I guess please choose a component from the figma file.

**Comment by rahulkarda** [comment]
> Hey this is not in the figma file, I guess please choose a component from the figma file. @rahulkarda
> 
> Please make a component from this [Figma File](https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988)

Updated the footer image, check if this works @Rajdip019

**Comment by SohanaShabnam05** [comment]
Please , assign me this issue

**Comment by Rajdip019** [comment]
Will review your PR. @rahulkarda

**Comment by Rajdip019** [comment]
Closing this issue as it is resolved.
