### ISSUE TITLE
Add a  Feature request template<Name>

### ISSUE THREAD

**Issue by kaustav202** [Clueless-Community/web-ui-kit#76]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here
NA

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by kaustav202** [comment]
Can I work on this @Rajdip019

**Comment by Rajdip019** [comment]
Please add an screenshot from the Figma file of the component. Otherwise how do I know what you want to build? @kaustav202

**Comment by kaustav202** [comment]
> Please add an screenshot from the Figma file of the component. Otherwise how do I know what you want to build? @kaustav202

I guess you missed the issue title.. it's a Feature Request Template that I want to add to issue Templates.. not build a component

**Comment by Rajdip019** [comment]
Are you still working on this issue? @kaustav202

**Comment by kaustav202** [comment]
yes @Rajdip019 ..I will make the PR soon
