### ISSUE TITLE
Create a Subscription card 

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/web-ui-kit#81]
Hey, 
I would like to create a subscription box using HTML and Tailwind CSS

### Images
![issue1 (1)](https://user-images.githubusercontent.com/99159580/195624665-38214b21-6acc-483e-b996-de1e78324fc6.jpg)

Plz review this and assign it to me under hacktober'22

**Comment by Rajdip019** [comment]
Hey, please select a component from this [Figma File](https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A1988)

**Comment by AKACHI-4** [comment]
![issue1](https://user-images.githubusercontent.com/99159580/195617285-58b2b795-7371-4a11-948a-44cc18b14706.png)

**Comment by Rajdip019** [comment]
Yeah go ahead and change the picture in the Issue as well as the name of the Issue. @AKACHI-4

**Comment by AKACHI-4** [comment]
Yah ok!!

**Comment by Ezekiel8807** [comment]
Please assign it to me if it's still available

**Comment by AKACHI-4** [comment]
hello @Ezekiel8807, I am already working on it plz work on some other issues.

**Comment by AKACHI-4** [comment]
@Rajdip019 I have completed it plz review
