### ISSUE TITLE
Create a Product Card Component

### ISSUE THREAD

**Issue by gokul1099** [Clueless-Community/web-ui-kit#85]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="678" alt="image" src="https://user-images.githubusercontent.com/42144106/195633881-28521ed6-607d-4d3d-8fef-00e26598a7c1.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by gokul1099** [comment]
@Rajdip019  I would like to work on this.

**Comment by SohanaShabnam05** [comment]
please, assign me this issue.

**Comment by Rajdip019** [comment]
Hey @gokul1099 please elect only one card you want to build.

**Comment by gokul1099** [comment]
ok @Rajdip019  I will take the first one.

**Comment by Rajdip019** [comment]
Sure please change the picture of this issue. @gokul1099

**Comment by rupsha014** [comment]
@gokul1099  Are you still working on this?

**Comment by akanshaaa19** [comment]
if available please assign this to me

**Comment by rupsha014** [comment]
@akanshaaa19 go ahead

**Comment by Viren0602** [comment]
Hello sir, can you assign this issue to me?
