### ISSUE TITLE
Create a Button with Icon ending

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/web-ui-kit#9]
One need to make this component using `HTML` and `CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![btn-sm-5](https://user-images.githubusercontent.com/91758830/195205928-13fc24cb-b788-40f4-987b-6626dc5f7ae6.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/button_with_icon_end.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by simonpankovski** [comment]
Hey, I would like to work on this issue. I used the Tailwind playground as you suggested and created this: 

![image](https://user-images.githubusercontent.com/46830637/195208160-cc204fda-dde9-4af9-990d-413474037309.png)

Could you assign me the issue so that I can make a PR :)

**Comment by Rajdip019** [comment]
Sure @simonpankovski . You are assigned.

**Comment by Rajdip019** [comment]
This issue is resolved. So closing this PR.
