### ISSUE TITLE
Create a Testimonial

### ISSUE THREAD

**Issue by aritra-tech** [Clueless-Community/web-ui-kit#90]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/80090908/195555018-ec26311a-acc0-4ccb-848e-4aefd519b1fc.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonial/index.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Ezekiel8807** [comment]
Please assign these to me

**Comment by Rajdip019** [comment]
Hey @aritra-tech are you working on it? I can see a PR linked to it.

**Comment by aritra-tech** [comment]
> 

Not started yet @Rajdip019.
If it is done then I can work on other components.

**Comment by Ezekiel8807** [comment]
Then what is the merged PR #92 for?

**Comment by Rajdip019** [comment]
Yeah please work on another component. That will be better. @aritra-tech
