### ISSUE TITLE
Create a product card floating phone

### ISSUE THREAD

**Issue by nishit3134** [Clueless-Community/web-ui-kit#94]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/111650900/195602491-05842675-f30e-41b8-8716-22611e7ef5bc.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by amitroy-thedev** [comment]
@nishit3134 can you assign this to me

**Comment by nishit3134** [comment]
@amitroy-thedev I myself want to work on this issue

**Comment by nishit3134** [comment]
@Rajdip019  please assign me this issue

**Comment by amitroy-thedev** [comment]
@nishit3134 oh okay.. 
Will you please guide how can i myself create an issue with hacktoberfest label

**Comment by nishit3134** [comment]
Checkout figma file in Contributing.md and select a component on which no one is working.
Click on new issue, add screenshot of component you want  to build and click create.
Then ask maintainer to assign you that issue.

**Comment by Rajdip019** [comment]
Go ahead @nishit3134
