### ISSUE TITLE
Create a DropDown button

### ISSUE THREAD

**Issue by error707-persona** [Clueless-Community/web-ui-kit#95]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here
![image](https://user-images.githubusercontent.com/53540032/195617241-ee16b208-fe89-4732-a2e6-ca66db00a5cf.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Dropdown/index.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by AKACHI-4** [comment]
I would like to work on this issue plz assign it to me

**Comment by error707-persona** [comment]
@AKACHI-4 I'm already working on it you can choose some other component
