### ISSUE TITLE
Create a Settings Button

### ISSUE THREAD

**Issue by error707-persona** [Clueless-Community/web-ui-kit#97]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest using [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/53540032/195626753-5c117d95-45de-4810-afa1-5a20ce2385ea.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Buttons/button_filled_icon_rounded_settings.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Go ahead. @error707-persona
