### ISSUE TITLE
Create a mobile filter marketplace

### ISSUE THREAD

**Issue by abhijain2003** [Clueless-Community/web-ui-kit#99]
![Screenshot 2022-10-13 202718](https://user-images.githubusercontent.com/91718608/195631862-b9e7eae9-2c6c-4173-8227-01517c15ab4c.png)
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
#### Add image here

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Choose one of the component @abhijain2003

**Comment by abhijain2003** [comment]
ok, for top one
![Screenshot 2022-10-13 202718](https://user-images.githubusercontent.com/91718608/195632884-1f4acc1e-17db-4015-8c1c-f82f2f9b2095.png)

**Comment by Rajdip019** [comment]
`Filter/mobile/marketplace-1.html`. @abhijain2003

**Comment by abhijain2003** [comment]
ok assigned it to me please
